%% LaBGAScore_decoding_SVM_between_subjects.m
%
%
% *USAGE*
%
% BETWEEN-SUBJECT SVM DECODING WITH PERMUTATION-BASED TFCE INFERENCE
%
% This script implements a complete second-level between-subject MVPA
% decoding pipeline using The Decoding Toolbox (TDT). It performs group-level
% SVM classification (patients vs controls), permutation-based statistical
% inference, and Threshold-Free Cluster Enhancement (TFCE) for spatially
% informed whole-brain, ROI, or searchlight decoding analyses.
%
% Statistical inference is non-parametric throughout and based on empirical
% permutation null distributions. TFCE constitutes the primary inferential
% framework, supplemented by voxel-wise permutation p-values and FDR
% correction for interpretability.
%
% The pipeline is designed for reproducibility, scalability, and integration
% with the Canlab neuroimaging framework.
%
% The script executes the following steps:
%
% 1. Data Preparation
%    - Loads phenotype information (participant IDs, group labels).
%    - Constructs balanced K-fold cross-validation (CV) partitions
%      separately for patients and controls.
%    - Assigns chunk labels and class labels to each subject.
%    - Loads first-level contrast images for all subjects.
%
% 2. Decoding Configuration (TDT)
%    Between-subject linear SVM decoding using The Decoding Toolbox,
%    supporting three analysis modes:
%
%      * 'searchlight' : spherical multivoxel decoding maps
%      * 'roi'         : decoding within multiple predefined ROIs
%      * 'wholebrain'  : decoding using a full-brain mask
%
%    Key configuration choices include:
%      - Linear C-SVC, identical for real and permutation runs. Two regimes,
%        selected by scaling_regime: 'kernel' (classification_kernel, scaling
%        estimated on all data - TDT's own recommendation, and much faster) or
%        'strict' (classification, train-only 'across' scaling, no kernel)
%      - Cross-validation folds balanced across groups, and across any
%        variable named in cv_strata_vars within group
%      - Scaling per scaling_regime, applied identically to real and null
%      - Explicit handling of unbalanced group sizes
%      - Performance metric: AUC minus chance
%
% 3. Real (Unpermuted) Decoding
%    - Runs decoding once using the true group labels.
%    - Extracts the voxel-wise decoding statistic vector (real_vec),
%      consistent across analysis modes.
%
% 4. Permutation Design Generation
%    - Generates N permutation designs using TDT's permutation framework.
%    - Permutations preserve the cross-validation structure while
%      destroying the label–group relationship.
%
% 5. Fast Permutation Decoding (In-Memory)
%    - Executes permutation decodings using parfor for efficiency.
%    - Uses THE SAME classifier and scaling as the real run. This is not a
%      detail: a null generated by a different procedure is not the null
%      distribution of the real statistic. See the note at the cfg block.
%    - Reuses passed_data and misc from the real run, so the images are read
%      and the searchlight neighbourhoods computed ONCE rather than once per
%      permutation.
%    - Avoids writing intermediate output folders or NIfTI files.
%    - Collects the empirical null distribution in memory as:
%
%          all_perm_results [nVoxels × nPermutations]
%
%    - Live progress and ETA reporting are provided during permutation runs.
%
% 6. Voxel-wise Permutation Statistics
%    - Computes empirical voxel-wise p-values from the permutation null:
%
%          p_unc(v) = ( #{perm >= real} + 1 ) / (nPerm + 1)
%
%    - Generates uncorrected and FDR-corrected voxel-wise p-maps for
%      complementary assessment of decoding effects.
%
% 7. TFCE-Based Inference (Primary)
%    - Converts decoding statistics to voxel-wise t-maps using the
%      permutation-derived mean and standard deviation.
%    - Applies Threshold-Free Cluster Enhancement (TFCE, Smith & Nichols
%      2009) via tfce_volume, shared with the secondlevel TFCE stack.
%    - Computes a permutation-based TFCE null distribution (in parallel).
%
%    TFCE inference includes:
%      - Global FWE-corrected TFCE p-value (max-statistic)
%      - Voxel-wise TFCE p-values (uncorrected)
%      - Voxel-wise FDR-corrected TFCE p-values
%      - Voxel-wise FWE-corrected TFCE p-values (using the TFCE max-statistic)
%
%    TFCE results constitute the primary inferential outcome of this
%    pipeline, providing spatially informed, permutation-based control
%    of family-wise error.
%
% 8. Canlab Output Generation
%    - Converts decoding statistics and p-maps into Canlab-compatible
%      representations:
%        * fmri_data_st objects
%        * region objects with atlas-based labels
%        * summary tables for reporting and visualization
%
%
% *OPTIONS*
%
% Set in the "0. USER SETTINGS" section below:
%
% * pheno_id_var            phenotype column holding sub-* identifiers, used to build image paths
% * pheno_group_var         phenotype column holding the group variable
% * group_pos_code / group_neg_code    values of that column for class +1 / -1
% * group_pos_name / group_neg_name    labels used in printouts
%
%       CHECK THE GROUP CODING. Getting it backwards silently swaps the two
%       classes: nothing errors, and every reported direction is reversed.
%
% * K                       number of cross-validation folds, balanced between patients and controls, default 5
% * cv_strata_vars          cell array of phenotype columns to balance across folds IN ADDITION to
%                           group, e.g. {'PET_MR'} for scanner. Stratification is not the same as
%                           regressing the variable out - TDT has no covariate hook - but it removes
%                           the failure mode that matters with a small nuisance stratum, namely a
%                           fold holding all or none of it
% * cv_seed                 seed for fold assignment; previously unset, so folds differed every run
% * con2use                 contrast image filename (con_XXXX.nii) to decode on
% * performance_metric      TDT performance metric, script only tested with {'AUC_minus_chance'}
% * unbalanced               true/false, whether to allow unbalanced group sizes in cfg.design
% * analysis_mode           'searchlight' | 'roi' | 'wholebrain'
%                               if 'searchlight': searchlight_radius (mm), mask_file (whole-brain mask for the searchlight)
%                               if 'roi': roi_list (cell array of ROI mask paths)
%                               if 'wholebrain': mask_file
% * n_perms                 number of permutations for the null distribution, default 1000
% * atlas                   CANlab atlas used for region labeling, default 'canlab2024'
% * unc_p / unc_k            uncorrected p-value / extent threshold for output fmri_data objects
% * fdr_p / fdr_k            FDR-corrected p-value / extent threshold for output fmri_data objects
% * fwe_p / fwe_k            TFCE FWE-corrected p-value / extent threshold for output fmri_data objects
%
%
% *DEPENDENCIES*
%
% - MATLAB R2018a or newer
% - The Decoding Toolbox (TDT)
% - LaBGAScore secondlevel/functions on the MATLAB path (tfce_volume,
%   tfce_transform_3d) and the Image Processing Toolbox for bwconncomp
% - SPM12 (recommended for NIfTI I/O)
% - NIfTI utilities (load_nii / save_nii)
% - Canlab toolbox (fmri_data_st, region, atlas utilities)
% - This repo's ProgressTracker class (secondlevel/classes/),
%   LaBGAScore_smart_parallel_pool_setup.m (clean/), and
%   secondlevel/functions/thresholded_fmri_data_from_pval_nii.m
%
% - phenotype.csv in BIDSdir containing:
%      * participant identifiers
%      * group labels (patient / control)
%
% - First-level contrast images (con_XXXX.nii) for all subjects
% - Valid brain mask (whole-brain / searchlight) or ROI masks
%
%
% *KNOWN-BAD PREDECESSORS*
%
% Results produced by earlier versions of this script, and by study copies of
% them, used a ONE-CLASS SVM ('-s 2') for the permutation null while the real
% statistic came from a C-SVC. The null therefore came from a model that never
% saw the training labels, and every permutation p-value built on it -
% uncorrected, FDR and TFCE - is invalid. proj_cfs model_8 is affected. Do not
% cite those p-values; re-run with this version instead.
%
%
% *NOTES*
%
% All outputs are written to tdt_resultsdir/, including:
%
% - NIfTI files:
%      * decoding statistic maps
%      * voxel-wise permutation p-maps
%      * TFCE-enhanced maps
%      * TFCE-based p-maps (voxel-wise, FDR, and FWE)
%
% - MATLAB files:
%      * combined_permutations.mat
%          - real_vec
%          - all_perm_results
%          - analysis metadata
%
% - Canlab objects:
%      * fmri_data_st objects (statistics and p-maps)
%      * region objects (TFCE- or voxel-wise thresholded clusters)
%      * summary tables with atlas-based annotations
%
% - All statistical inference is non-parametric and permutation-based.
% - TFCE is used as the primary method for spatial inference, with explicit
%   control of family-wise error via the permutation-derived max-statistic.
% - The script is fully non-interactive and suitable for HPC execution.
% - No temporary decoding folders or files are written during permutation
%   decoding.
%
% -------------------------------------------------------------------------
%
% modified by: Lukas Van Oudenhove
%
% date:   Leuven, Belgium, 2026
%
% -------------------------------------------------------------------------
%
% LaBGAScore_decoding_SVM_between_subjects.m
%
% last modified: 2026/08/20
%
%
%% ========================================================================
% 0. USER SETTINGS — EDIT THESE
% ========================================================================

% INPUT DIRECTORIES

a_set_up_paths_always_run_first
    
% WHICH TDT IS ACTUALLY BEING USED
%
% Two copies are typically installed on the LaBGAS server: SPM12 ships one
% under spm12/toolbox/decoding_toolbox, and there is a standalone
% /opt/KUL_apps/tdt_<version>. Whichever comes first on the path wins, and
% because SPM is normally prepended it is usually SPM's - which may be older.
% Report it so the version that produced a result is on the record, and warn
% when a second copy is shadowed.
tdt_used = which('decoding');
if isempty(tdt_used)
    error('The Decoding Toolbox is not on the MATLAB path (decoding.m not found).');
end
tdt_all = which('decoding','-all');
fprintf('\nTDT in use: %s\n', tdt_used);
if numel(tdt_all) > 1
    warning('LaBGAScore:tdt:shadowed', ...
        ['%d copies of TDT are on the path; the one above is being used. ' ...
         'Others: %s. Prepend the one you want with addpath(...,''-begin'').'], ...
         numel(tdt_all), strjoin(tdt_all(2:end)', ', '));
end

% PHENOTYPE FILE WITH GROUP INFO

phenofile = fullfile(BIDSdir, 'phenotype.csv');
phenotype = readtable(phenofile);

% PHENOTYPE COLUMN NAMES AND GROUP CODING
%
% These were hardcoded to one study (phenotype.patient, 0/1, .PPID). Named
% here so the script runs unchanged on any LaBGAS study. CHECK THEM: getting
% the group coding backwards silently swaps the two classes, which changes the
% sign of every result and nothing errors.

pheno_id_var    = 'participant_ID';   % column holding sub-* identifiers, used to build image paths
pheno_group_var = 'Group';            % column holding the group variable
group_pos_code  = 1;                  % value of pheno_group_var for class +1
group_neg_code  = -1;                 % value of pheno_group_var for class -1
group_pos_name  = 'patients';         % label for class +1, used in printouts only
group_neg_name  = 'controls';         % label for class -1

% CROSS-VALIDATION SETTINGS

K = 5;

% Variables to stratify the CV folds on, IN ADDITION to group. Folds are
% always balanced across groups; anything named here is balanced within group
% as well, so a nuisance variable cannot end up concentrated in a few folds.
% Typically the scanner or site. Set {} for group-only stratification.
%
% This is deliberately NOT the same as regressing the variable out. TDT has no
% covariate hook, and doing it per training fold means leaving TDT's CV loop.
% Stratification costs nothing and removes the failure mode that actually
% matters with a small nuisance stratum: a fold containing all or none of it.
cv_strata_vars = {};                  % e.g. {'PET_MR'}

% Seed for the fold assignment. The original script left this unset, so the
% real decoding used different folds on every run and was not reproducible.
cv_seed = 20260910;

% TDT SETTINGS

con2use = 'con_0003.nii';
conname = DSGN.contrastnames{sscanf(con2use, 'con_%d.nii')};
conname = strrep(conname, ' ', '_');
performance_metric = {'AUC_minus_chance'}; % script only tested with one metric
unbalanced = true;

analysis_mode = 'searchlight';    % 'searchlight' | 'roi' | 'wholebrain'

switch analysis_mode
    case 'searchlight'
        searchlight_radius = 6; % in mm
        mask_file = which('gm_mask_canlab2023_coarse_fmriprep20_0_20.nii');
        mask_obj = fmri_mask_image(mask_file);
    case 'roi'
        roi_list = {
                   which('aINS_L.nii')
                   which('aINS_R.nii')
                   which('Tha_L.nii')
                   which('Tha_R.nii')
                   which('Amyg_L.nii')
                   which('Amyg_R.nii')
                   which('IFG_vlPFC_L.nii')  
                   which('IFG_vlPFC_R.nii')
               }; % Add more ROI masks here - can be created with LaBGAS script
    case 'wholebrain'
        mask_file = which('gm_mask_canlab2023_coarse_fmriprep20_0_20.nii');
    otherwise
        error('analysis mode specified not implemented in TDT')
end

% PERMUTATION SETTINGS

n_perms = 1000;

% OUTPUT DIRECTORIES

tdt_resultsdir = fullfile(resultsdir,'TDT',conname,analysis_mode);  % folder where all TDT results are saved, can work with subfolders if you want to run multiple analyses
    if ~exist(tdt_resultsdir,'dir')
        mkdir(tdt_resultsdir);
    end
    
% ATLAS SETTINGS
atlas = load_atlas('canlab2024');

% THRESHOLDS FOR OUTPUT FMRI_DATA OBJECTS
unc_p = 0.01;
% Extent thresholds for the output fmri_data objects. Split into the plain AUC
% p-maps and the TFCE-derived maps, because an extent threshold means something
% different in each.
%
% On the AUC maps it is an ordinary display threshold: the map is voxelwise, so
% requiring a few contiguous voxels suppresses isolated specks.
%
% On the TFCE maps it corrects twice. TFCE already integrates cluster extent
% into the statistic, and the FWE map is already family-wise corrected across
% voxels, so a k on top removes signal that the correction has already accounted
% for. The same mistake in the second-level GLM stack was measured on
% proj_discoverie: k >= 50 removed every one of the 42 surviving TFCE-FWE voxels
% and reported an empty map. Hence 0 here, deliberately, not "not set".
unc_k_auc  = 50;
fdr_k_auc  = 25;

unc_k_tfce = 0;
fdr_k_tfce = 0;
fwe_k_tfce = 0;

    
%% ========================================================================
% 1. BUILD CV DESIGN
% ========================================================================

% Group membership, using the configured column and codes.
grp_raw = phenotype.(pheno_group_var);
if iscell(grp_raw) || isstring(grp_raw), grp_raw = double(string(grp_raw)); else, grp_raw = double(grp_raw); end

is_pos = grp_raw == group_pos_code;
is_neg = grp_raw == group_neg_code;

if ~all(is_pos | is_neg)
    error(['%d of %d rows in %s are neither group_pos_code (%g) nor group_neg_code (%g).\n' ...
           'Check pheno_group_var and the two codes before proceeding.'], ...
           sum(~(is_pos|is_neg)), numel(grp_raw), pheno_group_var, group_pos_code, group_neg_code);
end

table_combined = phenotype;
table_combined.labels = zeros(height(table_combined),1);
table_combined.labels(is_pos) = 1;
table_combined.labels(is_neg) = -1;

fprintf('\n%s (label +1): n = %d\n%s (label -1): n = %d\n', ...
    group_pos_name, sum(is_pos), group_neg_name, sum(is_neg));

% ---- stratified fold assignment ------------------------------------------
%
% Folds are balanced across groups, and across any variable named in
% cv_strata_vars within each group.
%
% Assignment is round-robin over a random permutation of each stratum, not
% cvpartition. cvpartition(n,'KFold',K) requires n >= K and so fails outright
% on a small stratum - with 3 subjects on one scanner and K = 5 it cannot be
% used at all - whereas round-robin spreads any stratum, however small, as
% evenly as it can be spread. The starting fold is randomised per stratum so
% small strata do not all pile into folds 1..n.

rng(cv_seed, 'twister');   % reproducible folds; the original script left this unset

strata_key = strings(height(table_combined),1);
for i = 1:height(table_combined)
    key = sprintf('g%d', table_combined.labels(i));
    for v = 1:numel(cv_strata_vars)
        val = table_combined.(cv_strata_vars{v})(i);
        if iscell(val), val = val{1}; end
        key = sprintf('%s|%s=%s', key, cv_strata_vars{v}, string(val));
    end
    strata_key(i) = key;
end

table_combined.chunks = zeros(height(table_combined),1);
ustrata = unique(strata_key);

for u = 1:numel(ustrata)
    idx  = find(strata_key == ustrata(u));
    perm = idx(randperm(numel(idx)));
    off  = randi(K) - 1;
    table_combined.chunks(perm) = mod((0:numel(perm)-1) + off, K) + 1;
end

table_combined.id = (1:height(table_combined))';

% ---- report the resulting balance, so it is visible rather than assumed ----
fprintf('\nfold composition (K = %d, seed %d):\n', K, cv_seed);
fprintf('  %-6s %8s %8s', 'fold', group_pos_name, group_neg_name);
for v = 1:numel(cv_strata_vars), fprintf(' %14s', cv_strata_vars{v}); end
fprintf('\n');
for k = 1:K
    in_k = table_combined.chunks == k;
    fprintf('  %-6d %8d %8d', k, sum(in_k & table_combined.labels==1), sum(in_k & table_combined.labels==-1));
    for v = 1:numel(cv_strata_vars)
        vals = table_combined.(cv_strata_vars{v})(in_k);
        if iscell(vals), vals = double(string(vals)); else, vals = double(vals); end
        fprintf(' %14s', sprintf('%d/%d', sum(vals>0), numel(vals)));
    end
    fprintf('\n');
end

if any(accumarray(table_combined.chunks, table_combined.labels==1) == 0) || ...
   any(accumarray(table_combined.chunks, table_combined.labels==-1) == 0)
    error('at least one fold contains no subjects from one of the groups; lower K');
end



%% ========================================================================
% 2. BUILD TDT CONFIGURATION (Mode‑Adaptive) - EDIT THESE
% ========================================================================

cfg = decoding_defaults;
cfg.results.dir = tdt_resultsdir;

switch lower(analysis_mode)

   case 'searchlight'
       cfg.analysis = 'searchlight';
       cfg.searchlight.unit = 'mm';
       cfg.searchlight.radius = searchlight_radius;
       cfg.searchlight.spherical = 1;
       cfg.files.mask = mask_file;
       fprintf('>> RUNNING SEARCHLIGHT\n');

   case 'roi'
       cfg.analysis = 'ROI';
       cfg.files.mask = roi_list;
       fprintf('>> RUNNING ROI DECODING\n');

   case 'wholebrain'
       cfg.analysis = 'wholebrain';
       cfg.files.mask = mask_file;
       fprintf('>> RUNNING WHOLE‑BRAIN DECODING\n');

   otherwise
       error('Unknown analysis mode.');
end

% Load subject images
cfg.files.name = cell(height(table_combined),1);
for i = 1:height(table_combined)
   cfg.files.name{i} = sprintf(['%s/%s/' con2use], ...
       datadir, table_combined.(pheno_id_var){i});
end

cfg.files.chunk = table_combined.chunks;

table_combined.labels(table_combined.patient==1) = 1;
table_combined.labels(table_combined.patient==-1) = -1;
cfg.files.label = table_combined.labels;

cfg.results.output = performance_metric;
cfg.verbose = 0;

% ---- classifier and scaling ----------------------------------------------
%
% Defined ONCE and applied to the real run and the permutations alike, because
% they have to be the same procedure. An earlier version of this script set
% them separately and they diverged: the real statistic came from a C-SVC
% while the null was generated with '-s 2', which is ONE-CLASS SVM in libsvm
% (svm.h: enum {C_SVC, NU_SVC, ONE_CLASS, EPSILON_SVR, NU_SVR}) - a model that
% never sees the training labels. A null from a different procedure is not the
% null distribution of the real statistic, so the p-values built on it were
% invalid. It also set cfg.decoding_method, which is not a TDT field at all
% (the field is cfg.decoding.method) and so did nothing.
%
% TWO VALID COMBINATIONS. They differ in speed, not really in validity:
%
%   'kernel'  classification_kernel + scaling estimated on all data.
%             TDT precomputes the kernel once per decoding, which is a large
%             saving when voxels >> subjects - decisive for wholebrain and
%             worthwhile for searchlight over many permutations. TDT itself
%             recommends estimating scaling on all samples, on the grounds
%             that a simple rescaling carries no category information from
%             training to test (see decoding_scale_data.m).
%
%   'strict'  classification + 'across' scaling, i.e. scaling parameters
%             estimated on the training fold only and applied to the test
%             fold. Removes even that much dependence on the test data, at
%             the cost of the kernel speed-up: 'across' CANNOT be combined
%             with classification_kernel, because under the kernel path
%             data_train is a struct holding kernel(i_train,i_train) (see
%             tdt_get_train_test in decoding.m) and TDT's per-fold scaling
%             would be applied to that kernel matrix rather than to the
%             features. TDT does not guard against this.
%
% WHY 'z' AND NOT 'min0max1'. Both scale per voxel, but they are set by very
% different things: 'z' uses the mean and SD over all subjects, 'min0max1' uses
% only the two most extreme subjects at that voxel (TDT computes
% min(data,[],1)/max(data,[],1), i.e. per feature). Measured on proj_cfs
% con_0003, 134 subjects over 150,630 grey-matter voxels:
%
%   range / SD per voxel      median 6.51, p95 8.85  (Gaussian expectation ~5.5)
%   dropping ONE subject at    median 19.8%, p95 45.7%, max 78.8%
%     each end shrinks range by
%   voxels where some subject  12.3%
%     exceeds |z| > 5
%
% So at a typical voxel a single subject at each end sets a fifth of the range
% that defines the scaling, and at the 95th percentile nearly half of it.
% min0max1 maps exactly those two subjects to 0 and 1 and compresses everyone
% else into what is left, which makes the scaling of every voxel depend on its
% least reliable observations.
%
% Note 'min0max1global' is a different thing again, and is the one TDT actually
% recommends for libsvm: one global min/max, a pure speed device that
% "produces the same classification results as for unscaled data". It is not a
% normalisation choice. 'min0max1' gives the fragility of order statistics
% without that guarantee, and is easy to select by conflating the two names.
%
% 'kernel' is the default because searchlight runtime is the binding
% constraint here. Switch to 'strict' if you want train-only scaling and can
% afford it.
scaling_regime = 'kernel';    % 'kernel' | 'strict'

switch scaling_regime
    case 'kernel'
        decoding_method  = 'classification_kernel';
        model_parameters = '-s 0 -t 4 -c 1 -b 0 -q';   % C-SVC, precomputed kernel
        scale_method     = 'z';
        scale_estimation = 'all';
    case 'strict'
        decoding_method  = 'classification';
        model_parameters = '-s 0 -t 0 -c 1 -b 0 -q';   % C-SVC, linear kernel
        scale_method     = 'z';
        scale_estimation = 'across';
    otherwise
        error('scaling_regime must be ''kernel'' or ''strict''');
end

cfg.decoding.method = decoding_method;
cfg.decoding.train.(decoding_method).model_parameters = model_parameters;
cfg.scale.method     = scale_method;
cfg.scale.estimation = scale_estimation;

fprintf('\ndecoding: %s, scaling %s/%s (regime ''%s'')\n', ...
    decoding_method, scale_method, scale_estimation, scaling_regime);

cfg.plot_selected_voxels = 0;

cfg.design = make_design_cv(cfg);
if unbalanced
    cfg.design.unbalanced_data = 'ok';
end


%% ========================================================================
% 3. RUN TRUE DECODING
% ========================================================================

fprintf('\n=== RUNNING TRUE DECODING ===\n');
% Capture passed_data and misc as well as the results. TDT's signature is
%   [results, cfg, passed_data, misc] = decoding(cfg, passed_data, misc)
% and handing both straight back into every permutation skips reloading the
% images AND recomputing the searchlight neighbourhoods, which is where the
% permutation loop previously spent nearly all of its time: it called
% decoding(cfgPi) with only a cfg, so each of n_perms runs re-read every
% subject's image from disk and rebuilt the searchlight index from scratch.
[results, cfg, passed_data, misc] = decoding(cfg);

% Extract vector format of real results
outname = cfg.results.output{1};
real_vec = results.(outname).output(:);


%% ========================================================================
% 4. GENERATE PERMUTATION DESIGNS
% ========================================================================

cfgp = rmfield(cfg,'design');
cfgp.design.function.name = 'make_design_cv';
% The permutation designs must come from the same procedure as the real run.
% This block previously switched the classifier and the scaling here, which is
% how the real statistic and its null came to be computed differently.
cfgp.decoding.method = decoding_method;
cfgp.decoding.train.(decoding_method).model_parameters = model_parameters;
cfgp.scale.method = scale_method;
cfgp.scale.estimation = scale_estimation;

designs = make_design_permutation(cfgp, n_perms, 0);


%% ========================================================================
% 5. FAST PERMUTATION DECODING (NO FOLDERS, IN‑MEMORY)
% ========================================================================

fprintf('\n=== RUNNING %d PERMUTATIONS WITHOUT WRITING FILES ===\n', n_perms);

% Start pool if needed
LaBGAScore_smart_parallel_pool_setup

Cdesigns    = parallel.pool.Constant(designs);

% Share the loaded data and the searchlight neighbourhoods across workers.
% parallel.pool.Constant sends each ONCE per worker; without it parfor would
% broadcast both on every iteration, which for a searchlight is hundreds of MB
% per permutation.
Cpassed     = parallel.pool.Constant(passed_data);
Cmisc       = parallel.pool.Constant(misc);

% Build template cfg from the REAL cfg, so the permutations cannot drift away
% from the procedure that produced the real statistic. Only the design changes.
cfg_template = cfg;
cfg_template.results.write = 0;      % no folders, no NIfTIs, in memory only
cfg_template.verbose       = 0;
cfg_template.plot_selected_voxels = 0;
cfg_template.design        = [];

% Preallocate null matrix
V = numel(real_vec);
all_perm_results = zeros(V, n_perms, 'single');

% Progress
tracker = ProgressTracker(n_perms);
q = parallel.pool.DataQueue;
afterEach(q, @(~) tracker.update());

fprintf('Running %d permutations (%s, scaling %s, %s)...\n', ...
    n_perms, decoding_method, scale_estimation, analysis_mode);

% PARFOR: decode permutations in memory only, reusing data and neighbourhoods
parfor p = 1:n_perms
   cfgPi = cfg_template;
   cfgPi.design = Cdesigns.Value{p};
   cfgPi.design.unbalanced_data = 'ok';
   r = decoding(cfgPi, Cpassed.Value, Cmisc.Value);
   all_perm_results(:,p) = single(r.(outname).output(:));
   send(q,1);
end

save(fullfile(tdt_resultsdir,'combined_permutations.mat'), ...
    'all_perm_results','outname','-v7.3');

fprintf('\nCombined null distribution saved.\n');


%% ========================================================================
% 6. VOXELWISE P-VALUES
% ========================================================================

fprintf('\n=== COMPUTING VOXELWISE P-VALUES ===\n');

[V,P] = size(all_perm_results);

exceed = sum(all_perm_results >= real_vec, 2);
p_unc = (exceed + 1) ./ (P + 1);

switch analysis_mode
    
    case 'wholebrain'
        
        results.(performance_metric{1}).p_perm = p_unc;
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');
        
    case 'roi'
        
        results.(performance_metric{1}).p_perm_unc = p_unc;
        
        % Apply Storey's FDR
        [~, q_fdr, aprioriprob] = mafdr(p_unc);

        % If aprioriprob > 0.99, fallback to BenjaminiHochberg
        if aprioriprob > 0.99
            p_fdr = mafdr(p_unc, 'BHFDR', true);
            results.(performance_metric{1}).p_perm_fdr = p_fdr;
        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_fdr)
                if q_fdr(j) < p_unc(j)
                    q_fdr(j) = p_unc(j);
                end
            end
            results.(performance_metric{1}).q_perm_fdr = q_fdr;
        end
        
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');
        
        
    case 'searchlight'

        results.(performance_metric{1}).p_perm = p_unc;
        
        % Save uncorrected whole-brain p-map
        nii = load_nii(mask_file);
        mask = nii.img > 0;
        mask_idx = find(mask);

        % real_vec must be the real decoding statistics vector
        % used to generate p_unc (same length)
        if length(real_vec) ~= length(p_unc)
            error('real_vec and p_unc length mismatch');
        end

        % Identify valid decoding voxels (NaNs removed by TDT)
        valid_idx = ~isnan(real_vec);

        % Initialize p-map
        pmap = nan(size(nii.img), 'single');

        % Assign only to valid voxels
        pmap(mask_idx(valid_idx)) = p_unc;

        nii.img = pmap;
        save_nii(nii, fullfile(tdt_resultsdir,'p_uncorrected.nii'));
        
        [AUC_stat_obj, AUC_fmri_data, AUC_region_obj, AUC_region_table] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_uncorrected.nii'), results.(performance_metric{1}).output, ...
            mask_obj, atlas, unc_p, ['right-tailed uncorrected p-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'unc', unc_k_auc);


        %% ========================================================================
        % 7. WHOLE-BRAIN FDR CORRECTION
        % ========================================================================

        fprintf('\n=== APPLYING FDR CORRECTION ===\n');
        
        fmap = nan(size(nii.img));

        % Apply Storey's FDR
        [~, q_fdr, aprioriprob] = mafdr(p_unc);

        % If aprioriprob > 0.99, fallback to BenjaminiHochberg
        if aprioriprob > 0.99
            p_fdr = mafdr(p_unc, 'BHFDR', true);
            results.(performance_metric{1}).p_perm_fdr = p_fdr;
            fmap(mask_idx(valid_idx)) = p_fdr;
            nii.img = fmap;
            save_nii(nii, fullfile(tdt_resultsdir,'p_FDR.nii'));
            [AUC_stat_obj_fdr, AUC_fmri_data_fdr, AUC_region_obj_fdr, AUC_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_FDR.nii'), results.(performance_metric{1}).output, ...
                mask_obj, atlas, fdr_p, ['right-tailed FDR-corrected p-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'fdr', fdr_k_auc);
        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_fdr)
                if q_fdr(j) < p_unc(j)
                    q_fdr(j) = p_unc(j);
                end
            end
            results.(performance_metric{1}).q_perm_fdr = q_fdr;
            fmap(mask_idx(valid_idx)) = q_fdr;
            nii.img = fmap;
            save_nii(nii, fullfile(tdt_resultsdir,'q_FDR.nii'));
            [AUC_stat_obj_fdr, AUC_fmri_data_fdr, AUC_region_obj_fdr, AUC_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'q_FDR.nii'), results.(performance_metric{1}).output, ...
                mask_obj, atlas, fdr_p, ['right-tailed FDR-corrected q-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'fdr', fdr_k_auc);
        end

        %% ========================================================================
        % 8. TFCE AND TFCE P-VALUES
        % ========================================================================

        fprintf('\n=== RUNNING TFCE on t-maps ===\n');

        % -------------------- TFCE parameters --------------------
        % Classic TFCE (Smith & Nichols 2009) via tfce_volume. This used to
        % call pTFCE, which is a different algorithm with no H or E parameter:
        % the voxel size was landing in pTFCE's `mask` slot and H/E in its
        % resel-count and voxel-count slots, so the transform was not the one
        % these parameter names describe. See tfce_volume.
        H    = 2;        % Height exponent (Smith & Nichols default)
        E    = 0.5;      % Extent exponent
        conn = 26;       % 3D connectivity
        tfce_sidedness = 'one';   % AUC is tested against 0.5, so one-tailed
        tfce_tail      = 'pos';

        % ========================================================================
        % 0. COMPUTE REAL AND PERMUTATION T-MAPS + EPSILON
        % ========================================================================

        eps_val = 1e-6;     % prevents zero-plateaus that trigger warnings

        % Real t-map
        perm_mu = mean(all_perm_results, 2);
        perm_sd = std(all_perm_results, 0, 2);
        perm_sd(perm_sd == 0) = 1;   % voxels with no variance across permutations

        real_t_vec = (real_vec - perm_mu) ./ perm_sd + eps_val;
        results.(performance_metric{1}).real_t = real_t_vec;

        % Permutation t-maps are NOT materialised as a [V x P] matrix here.
        % Doing so cost a second array the size of all_perm_results (for a
        % 150k-voxel searchlight with 1000 permutations, ~600 MB) and it was
        % then stored in results and written into res_*.mat as well. The two
        % vectors below are all that is needed; each permutation's t-map is
        % formed inside the TFCE loop from its own column, which parfor slices.
        % ========================================================================
        % 1. REAL TFCE MAP
        % ========================================================================

        tmpVol = zeros(size(nii.img), 'single');
        tmpVol(mask_idx(valid_idx)) = single(real_t_vec);

        % The observed map fixes the integration grid; every permutation
        % below reuses tfce_dh so the null is comparable to the observed
        % statistic rather than each map using its own grid.
        [real_TFCE_img, tfce_dh] = tfce_volume(tmpVol, H, E, conn, ...
                                               tfce_sidedness, tfce_tail, []);

        if isempty(tfce_dh)
            error('No positive values in the real t-map: TFCE is identically zero.');
        end
        
        real_TFCE_img(isnan(real_TFCE_img)) = 0;
        real_TFCE_img(real_TFCE_img < 0) = 0;

        real_TFCE_vec = real_TFCE_img(mask_idx(valid_idx));
        results.(performance_metric{1}).real_TFCE = real_TFCE_vec;

        % Save TFCE-enhanced real map
        tfmap = nan(size(nii.img), 'single');
        tfmap(mask_idx(valid_idx)) = real_TFCE_vec;
        nii.img = tfmap;
        save_nii(nii, fullfile(tdt_resultsdir,'TFCE_real.nii'));

        % ========================================================================
        % 2. PARALLEL TFCE NULL DISTRIBUTION (t-maps → TFCE)
        % ========================================================================

        fprintf('Computing TFCE null distribution (parallel)...\n');

        TFCE_null     = zeros(P,1,'single');     % global max TFCE
        TFCE_perm_all = zeros(V,P,'single');     % voxel-wise TFCE
        
        % Progress
        tracker = ProgressTracker(P);
        q_tfce = parallel.pool.DataQueue;
        afterEach(q_tfce, @(~) tracker.update());

        parfor p = 1:P

           tmpVol = zeros(size(nii.img), 'single');
           % t-map for THIS permutation, built from its own column of
           % all_perm_results (a sliced parfor input, so only that column is
           % sent to the worker) rather than from a precomputed [V x P] matrix
           tvec = (all_perm_results(:,p) - perm_mu) ./ perm_sd + eps_val;
           tmpVol(mask_idx(valid_idx)) = single(tvec);

           % Compute TFCE on permutation t-map
           % same integration grid as the observed map
           TFCE_img = tfce_volume(tmpVol, H, E, conn, ...
                                  tfce_sidedness, tfce_tail, tfce_dh);
           
           TFCE_img(isnan(TFCE_img)) = 0;

           TFCE_null(p) = max(TFCE_img(:));         % global max-stat
           TFCE_perm_all(:,p) = TFCE_img(mask_idx(valid_idx)); % voxel-wise TFCE
           
           send(q_tfce,1);
           
        end
        
        TFCE_perm_all(TFCE_perm_all < 0) = 0;

        save(fullfile(tdt_resultsdir,'TFCE_null.mat'),'TFCE_null','TFCE_perm_all');

        % ========================================================================
        % 3. GLOBAL FWE-CORRECTED TFCE p-VALUE (max-statistic)
        % ========================================================================

        TFCE_real_max = max(real_TFCE_vec);

        p_TFCE_global = (sum(TFCE_null >= TFCE_real_max) + 1) / (P + 1);
        
        results.(performance_metric{1}).p_TFCE_global = p_TFCE_global;

        % ========================================================================
        % 4. VOXEL-WISE TFCE p-MAP
        % ========================================================================

        fprintf('Computing voxel-wise TFCE p-values...\n');

        p_TFCE_voxelwise = (sum(TFCE_perm_all >= real_TFCE_vec, 2) + 1) / (P + 1);
        
        results.(performance_metric{1}).p_TFCE_unc = p_TFCE_voxelwise;

        pmap_vox = nan(size(nii.img), 'single');
        pmap_vox(mask_idx(valid_idx)) = p_TFCE_voxelwise;

        nii.img = pmap_vox;
        save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_voxelwise.nii'));
        
        [TFCE_stat_obj, TFCE_fmri_data, TFCE_region_obj, TFCE_region_table] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
            mask_obj, atlas, unc_p, ['right-tailed uncorrected TFCE p-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'unc', unc_k_tfce);

        % ========================================================================
        % 5. FDR-CORRECTED TFCE p-MAP
        % ========================================================================

        fprintf('Applying FDR correction to TFCE p-values...\n');
        
        fmap = nan(size(nii.img));

        % Apply Storey's FDR
        [~, q_TFCE_FDR, aprioriprob] = mafdr(p_TFCE_voxelwise);

        % If aprioriprob > 0.99, fallback to Benjamini-Hochberg
        if aprioriprob > 0.99
            p_TFCE_FDR = mafdr(p_TFCE_voxelwise, 'BHFDR', true);
            results.(performance_metric{1}).p_TFCE_FDR = p_TFCE_FDR;
            pmap_FDR = nan(size(nii.img), 'single');
            pmap_FDR(mask_idx(valid_idx)) = p_TFCE_FDR;
            nii.img = pmap_FDR;
            save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_FDR_voxelwise.nii'));
            
            [TFCE_stat_obj_fdr, TFCE_fmri_data_fdr, TFCE_region_obj_fdr, TFCE_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_FDR_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
                mask_obj, atlas, fdr_p, ['right-tailed fdr-corrected TFCE p-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fdr', fdr_k_tfce);

        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_TFCE_FDR)
                if q_TFCE_FDR(j) < p_TFCE_voxelwise(j)
                    q_TFCE_FDR(j) = p_TFCE_voxelwise(j);
                end
            end
            results.(performance_metric{1}).q_TFCE_FDR = q_TFCE_FDR;
            qmap_FDR = nan(size(nii.img), 'single');
            qmap_FDR(mask_idx(valid_idx)) = q_TFCE_FDR;
            nii.img = qmap_FDR;
            save_nii(nii, fullfile(tdt_resultsdir,'q_TFCE_FDR_voxelwise.nii'));
            
            [TFCE_stat_obj_fdr, TFCE_fmri_data_fdr, TFCE_region_obj_fdr, TFCE_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'q_TFCE_FDR_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
                mask_obj, atlas, fdr_p, ['right-tailed fdr-corrected TFCE q-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fdr', fdr_k_tfce);

        end
        
        %% ========================================================================
        % 6. VOXEL-WISE TFCE FWE-CORRECTED P-MAP (MAX-STATISTIC)
        % ========================================================================

        fprintf('Computing voxel-wise TFCE FWE-corrected p-values (max-statistic)...\n');

        P = numel(TFCE_null); % number of permutations

        % -------------------------------------------------------------------------
        % Compute voxel-wise TFCE FWE p-values using max TFCE null
        % -------------------------------------------------------------------------
        p_TFCE_FWE_voxelwise = ( ...
           sum(TFCE_null(:)' >= real_TFCE_vec, 2) + 1 ...
           ) ./ (P + 1);
        results.(performance_metric{1}).p_TFCE_FWE = p_TFCE_FWE_voxelwise;
        
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');

        % -------------------------------------------------------------------------
        % Map vector -> volume
        % -------------------------------------------------------------------------
        pmap_FWE = nan(size(nii.img), 'single');
        pmap_FWE(mask_idx(valid_idx)) = p_TFCE_FWE_voxelwise;

        nii.img = pmap_FWE;
        save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_FWE_voxelwise.nii'));
        
        [TFCE_stat_obj_fwe, TFCE_fmri_data_fwe, TFCE_region_obj_fwe, TFCE_region_table_fwe] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_FWE_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
            mask_obj, atlas, fwe_p, ['right-tailed fwe-corrected TFCE p-values (max statistic) based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fwe', fwe_k_tfce);
        
        fprintf('Voxel-wise TFCE FWE-corrected map saved.\n');

        fprintf('\nTFCE completed: FWE, voxel-wise, and FDR TFCE maps saved.\n');

        
        save(fullfile(tdt_resultsdir,'stat_objs.mat'),'AUC_*','TFCE_*');

        
end