%% LaBGAScore_decoding_SVM_between_subjects.m
%
%
% *USAGE*
%
% BETWEEN-SUBJECT SVM DECODING WITH PERMUTATION-BASED TFCE INFERENCE
%
% This script implements a complete second-level between-subject MVPA
% decoding pipeline using The Decoding Toolbox (TDT). It performs group-level
% SVM classification (patients vs controls), permutation-based statistical
% inference, and Threshold-Free Cluster Enhancement (TFCE) for spatially
% informed whole-brain, ROI, or searchlight decoding analyses.
%
% Statistical inference is non-parametric throughout and based on empirical
% permutation null distributions. TFCE constitutes the primary inferential
% framework, supplemented by voxel-wise permutation p-values and FDR
% correction for interpretability.
%
% The pipeline is designed for reproducibility, scalability, and integration
% with the Canlab neuroimaging framework.
%
% The script executes the following steps:
%
% 1. Data Preparation
%    - Loads phenotype information (participant IDs, group labels).
%    - Constructs balanced K-fold cross-validation (CV) partitions
%      separately for patients and controls.
%    - Assigns chunk labels and class labels to each subject.
%    - Loads first-level contrast images for all subjects.
%
% 2. Decoding Configuration (TDT)
%    Between-subject linear SVM decoding using The Decoding Toolbox,
%    supporting three analysis modes:
%
%      * 'searchlight' : spherical multivoxel decoding maps
%      * 'roi'         : decoding within multiple predefined ROIs
%      * 'wholebrain'  : decoding using a full-brain mask
%
%    Key configuration choices include:
%      - Linear C-SVC, identical for real and permutation runs. Two regimes,
%        selected by scaling_regime: 'kernel' (classification_kernel, scaling
%        estimated on all data - TDT's own recommendation, and much faster) or
%        'strict' (classification, train-only 'across' scaling, no kernel)
%      - Cross-validation folds balanced across groups, and across any
%        variable named in cv_strata_vars within group
%      - Scaling per scaling_regime, applied identically to real and null
%      - Explicit handling of unbalanced group sizes
%      - Performance metric: AUC minus chance
%
% 3. Real (Unpermuted) Decoding
%    - Runs decoding once using the true group labels.
%    - Extracts the voxel-wise decoding statistic vector (real_vec),
%      consistent across analysis modes.
%
% 4. Permutation Design Generation
%    - Generates N permutation designs using TDT's permutation framework.
%    - Permutations preserve the cross-validation structure while
%      destroying the label–group relationship.
%
% 5. Fast Permutation Decoding (In-Memory)
%    - Executes permutation decodings using parfor for efficiency.
%    - Uses THE SAME classifier and scaling as the real run. This is not a
%      detail: a null generated by a different procedure is not the null
%      distribution of the real statistic. See the note at the cfg block.
%    - Reuses passed_data and misc from the real run, so the images are read
%      and the searchlight neighbourhoods computed ONCE rather than once per
%      permutation.
%    - Avoids writing intermediate output folders or NIfTI files.
%    - Collects the empirical null distribution in memory as:
%
%          all_perm_results [nVoxels × nPermutations]
%
%    - Live progress and ETA reporting are provided during permutation runs.
%
% 6. Voxel-wise Permutation Statistics
%    - Computes empirical voxel-wise p-values from the permutation null:
%
%          p_unc(v) = ( #{perm >= real} + 1 ) / (nPerm + 1)
%
%    - Generates uncorrected and FDR-corrected voxel-wise p-maps for
%      complementary assessment of decoding effects.
%
% 7. TFCE-Based Inference (Primary)
%    - Converts decoding statistics to voxel-wise t-maps using the
%      permutation-derived mean and standard deviation.
%    - Applies Threshold-Free Cluster Enhancement (TFCE, Smith & Nichols
%      2009) via tfce_volume, shared with the secondlevel TFCE stack.
%    - Computes a permutation-based TFCE null distribution (in parallel).
%
%    TFCE inference includes:
%      - Global FWE-corrected TFCE p-value (max-statistic)
%      - Voxel-wise TFCE p-values (uncorrected)
%      - Voxel-wise FDR-corrected TFCE p-values
%      - Voxel-wise FWE-corrected TFCE p-values (using the TFCE max-statistic)
%
%    TFCE results constitute the primary inferential outcome of this
%    pipeline, providing spatially informed, permutation-based control
%    of family-wise error.
%
% 8. Canlab Output Generation
%    - Converts decoding statistics and p-maps into Canlab-compatible
%      representations:
%        * fmri_data_st objects
%        * region objects with atlas-based labels
%        * summary tables for reporting and visualization
%
%
% *OPTIONS*
%
% Set in the "0. USER SETTINGS" section below:
%
% * pheno_id_var            phenotype column holding sub-* identifiers, used to build image paths
% * pheno_group_var         phenotype column holding the group variable
% * group_pos_code / group_neg_code    values of that column for class +1 / -1
% * group_pos_name / group_neg_name    labels used in printouts
%
%       CHECK THE GROUP CODING. Getting it backwards silently swaps the two
%       classes: nothing errors, and every reported direction is reversed.
%
% * K                       number of cross-validation folds, balanced between patients and controls, default 5
% * cv_strata_vars          cell array of phenotype columns to balance across folds IN ADDITION to
%                           group, e.g. {'PET_MR'} for scanner. Stratification is not the same as
%                           regressing the variable out - TDT has no covariate hook - but it removes
%                           the failure mode that matters with a small nuisance stratum, namely a
%                           fold holding all or none of it
% * cv_seed                 seed for fold assignment; previously unset, so folds differed every run
% * con2use                 contrast image filename (con_XXXX.nii) to decode on
% * performance_metric      TDT performance metric, script only tested with {'AUC_minus_chance'}
% * unbalanced               true/false, whether to allow unbalanced group sizes in cfg.design
% * analysis_mode           'searchlight' | 'roi' | 'wholebrain'
%                               if 'searchlight': searchlight_radius (mm), mask_file (whole-brain mask for the searchlight)
%                                                 searchlight_subset - TIMING BENCHMARK ONLY, leave empty ([])
%                                                 for any real analysis. An Nx1 LIST OF SEARCHLIGHT
%                                                 INDICES (or Nx3 XYZ coords) - NOT a decimation
%                                                 factor: the scalar 20 runs ONE centre, not every
%                                                 20th, and TDT accepts it silently. TDT returns 0, not NaN, for centres it did
%                                                 not run, and 0 is a legitimate AUC_minus_chance
%                                                 (exactly chance), so skipped centres CANNOT be told
%                                                 apart from real ones downstream: they would enter the
%                                                 FDR correction and the TFCE null as genuine
%                                                 chance-level data. The script therefore refuses to run
%                                                 inference when it is set, and stops after the timings.
%                               if 'roi': roi_list (cell array of ROI mask paths)
%                               if 'wholebrain': mask_file
% * n_perms                 number of permutations for the null distribution, default 1000
% * atlas                   CANlab atlas used for region labeling, default 'canlab2024'
% * unc_p / unc_k            uncorrected p-value / extent threshold for output fmri_data objects
% * fdr_p / fdr_k            FDR-corrected p-value / extent threshold for output fmri_data objects
% * fwe_p / fwe_k            TFCE FWE-corrected p-value / extent threshold for output fmri_data objects
% * combat_batch_var        phenotype column holding site/batch labels, e.g. 'center'; empty disables
%                           ComBat. Harmonisation here is LABEL-BLIND (mod = []) by design: telling
%                           ComBat to preserve the variable being decoded would leak labels into the
%                           features. Features that are constant across all samples, or constant
%                           within any one site, are excluded from harmonisation and passed through
%                           untouched - combat.m errors on the first and returns NaN on the second.
% * combat_ref              site label to harmonise towards; empty harmonises to the grand mean
% * export_conidx           contrast index to export when scaled_contrast_dir is empty;
%                           defaults to con2use when that is a scalar index
% * export_object           contrast object to export: 'DATA_OBJ_CON' (raw),
%                           'DATA_OBJ_CONsc' (z-scored conditions) or 'DATA_OBJ_CONscc'.
%                           Defaults from myscaling_glm, so it matches the GLM by default
% * scaled_contrast_dir     directory of per-subject contrast NIfTIs written by
%                           LaBGAScore_export_scaled_contrasts. Set this to decode the SAME images the
%                           second-level GLM used; leave empty to read raw first-level
%                           contrasts. If the directory is empty or absent it is POPULATED
%                           automatically by LaBGAScore_export_scaled_contrasts
% * contrast_objects_tag    default ''; suffix identifying WHICH set of contrast objects to
%                           export features from, for a model that harmonises more than one way.
%                           A GLM path harmonised with combat_mod = {'group'} is not a valid
%                           feature source for a classifier: ComBat adds the fitted group effect
%                           back into its own output, so every image carries a term proportional
%                           to its own subject's label. Point this at the label-blind path.
% * scaling_regime          'kernel' (TDT's recommended estimation = 'all', precomputed kernel reused
%                           across permutations) or 'strict' ('across', train-fold-only scaling;
%                           measured 12-25x slower because the kernel cannot be reused)
%
%
% *DEPENDENCIES*
%
% - MATLAB R2018a or newer
% - The Decoding Toolbox (TDT)
% - LaBGAScore secondlevel/functions on the MATLAB path (tfce_volume,
%   tfce_transform_3d) and the Image Processing Toolbox for bwconncomp
% - SPM12 (recommended for NIfTI I/O)
% - NIfTI utilities (load_nii / save_nii)
% - Canlab toolbox (fmri_data_st, region, atlas utilities)
% - This repo's ProgressTracker class (secondlevel/classes/),
%   LaBGAScore_smart_parallel_pool_setup.m (clean/), and
%   secondlevel/functions/thresholded_fmri_data_from_pval_nii.m
%
% - phenotype.csv in BIDSdir containing:
%      * participant identifiers
%      * group labels (patient / control)
%
% - First-level contrast images (con_XXXX.nii) for all subjects
% - Valid brain mask (whole-brain / searchlight) or ROI masks
%
%
% *KNOWN-BAD PREDECESSORS*
%
% Results produced by earlier versions of this script, and by study copies of
% them, used a ONE-CLASS SVM ('-s 2') for the permutation null while the real
% statistic came from a C-SVC. The null therefore came from a model that never
% saw the training labels, and every permutation p-value built on it -
% uncorrected, FDR and TFCE - is invalid. proj_cfs model_8 is affected. Do not
% cite those p-values; re-run with this version instead.
%
%
% *NOTES*
%
% All outputs are written to tdt_resultsdir/, including:
%
% - NIfTI files:
%      * decoding statistic maps
%      * voxel-wise permutation p-maps
%      * TFCE-enhanced maps
%      * TFCE-based p-maps (voxel-wise, FDR, and FWE)
%
% - MATLAB files:
%      * combined_permutations.mat
%          - real_vec
%          - all_perm_results
%          - analysis metadata
%
% - Canlab objects:
%      * fmri_data_st objects (statistics and p-maps)
%      * region objects (TFCE- or voxel-wise thresholded clusters)
%      * summary tables with atlas-based annotations
%
% - All statistical inference is non-parametric and permutation-based.
% - TFCE is used as the primary method for spatial inference, with explicit
%   control of family-wise error via the permutation-derived max-statistic.
% - The script is fully non-interactive and suitable for HPC execution.
% - No temporary decoding folders or files are written during permutation
%   decoding.
%
% -------------------------------------------------------------------------
%
% modified by: Lukas Van Oudenhove
%
% date:   Leuven, Belgium, 2026
%
% -------------------------------------------------------------------------
%
% LaBGAScore_decoding_SVM_between_subjects.m
%
% last modified: 2026/09/17
%
%
%% ========================================================================
% 0. USER SETTINGS — EDIT THESE
% ========================================================================

% INPUT DIRECTORIES

% Remember where the study's own setup put the results, so the call below can be
% checked against it (see the guard immediately after).
resultsdir_before_setup = '';
if exist('resultsdir','var'), resultsdir_before_setup = resultsdir; end


a_set_up_paths_always_run_first

% GUARD: did the path setup just move the output directory?
%
% The call above is meant to be replaced, in a study's copy, by that study's own
% s0 (e.g. mystudy_secondlevel_m2a_s0_a_set_up_paths_always_run_first). Left as
% the generic call, it RE-DERIVES resultsdir - typically from the FIRST-LEVEL
% model name - and silently overwrites whatever the study's setup had already
% set. Every result then lands in a different model's directory while the
% published report still goes to the right one, so the split is easy to miss.
if ~isempty(resultsdir_before_setup) && ~strcmp(resultsdir_before_setup, resultsdir)
    error(['\nPATH SETUP MOVED THE RESULTS DIRECTORY.\n\n' ...
           '  before: %s\n  after : %s\n\n' ...
           'The generic a_set_up_paths_always_run_first re-derived resultsdir and\n' ...
           'discarded the one your study setup had set. In your copy of this script,\n' ...
           'replace that call with your study''s own s0 path script.\n'], ...
           resultsdir_before_setup, resultsdir);
end

    
% WHICH TDT IS ACTUALLY BEING USED
%
% Two copies are typically installed on the LaBGAS server: SPM12 ships one
% under spm12/toolbox/decoding_toolbox, and there is a standalone
% /opt/KUL_apps/tdt_<version>. Whichever comes first on the path wins, and
% because SPM is normally prepended it is usually SPM's - which may be older.
% Report it so the version that produced a result is on the record, and warn
% when a second copy is shadowed.
tdt_used = which('decoding');
if isempty(tdt_used)
    error('The Decoding Toolbox is not on the MATLAB path (decoding.m not found).');
end
tdt_all = which('decoding','-all');
fprintf('\nTDT in use: %s\n', tdt_used);
if numel(tdt_all) > 1
    warning('LaBGAScore:tdt:shadowed', ...
        ['%d copies of TDT are on the path; the one above is being used. ' ...
         'Others: %s. Prepend the one you want with addpath(...,''-begin'').'], ...
         numel(tdt_all), strjoin(tdt_all(2:end)', ', '));
end

% PHENOTYPE FILE WITH GROUP INFO

% The filename was hardcoded to one study's phenotype.csv. LaBGAS studies do
% not agree on this: proj_cfs has BIDS/phenotype.csv (comma), proj_moodbugs has
% BIDS/participants.tsv (tab). Named here so the script runs on either, with the
% delimiter taken from the extension rather than left to readtable's guess.
pheno_file = 'phenotype.csv';         % file inside BIDSdir, e.g. 'participants.tsv'

phenofile = fullfile(BIDSdir, pheno_file);
if exist(phenofile, 'file') ~= 2
    error(['\nphenotype file not found: %s\nSet pheno_file to the right name ' ...
           '(proj_cfs uses phenotype.csv, proj_moodbugs uses participants.tsv).\n'], phenofile);
end
if endsWith(lower(phenofile), '.tsv')
    phenotype = readtable(phenofile, 'FileType', 'text', 'Delimiter', 'tab');
else
    phenotype = readtable(phenofile, 'FileType', 'text', 'Delimiter', 'comma');
end

% PHENOTYPE COLUMN NAMES AND GROUP CODING
%
% These were hardcoded to one study (phenotype.patient, 0/1, .PPID). Named
% here so the script runs unchanged on any LaBGAS study. CHECK THEM: getting
% the group coding backwards silently swaps the two classes, which changes the
% sign of every result and nothing errors.

pheno_id_var    = 'participant_ID';   % column holding sub-* identifiers, used to build image paths
pheno_group_var = 'Group';            % column holding the group variable
group_pos_code  = 1;                  % value of pheno_group_var for class +1
group_neg_code  = -1;                 % value of pheno_group_var for class -1
group_pos_name  = 'patients';         % label for class +1, used in printouts only
group_neg_name  = 'controls';         % label for class -1

% CROSS-VALIDATION SETTINGS

K = 5;

% CONFOUND HANDLING
%
% Fold stratification (cv_strata_vars, below) balances a nuisance variable
% ACROSS folds. That is a variance fix: it stops a fold holding all or none of
% a small stratum. It does NOT remove confounding. If the nuisance predicts
% group, the classifier learns the nuisance during training, the held-out fold
% carries the same nuisance-group mapping, and the AUC is inflated by exactly
% the signal you were trying to control.
%
% Measured in proj_discoverie model_3a, where centre is the nuisance:
%   centre alone predicts group at AUC 0.745
%   centre KUL vs UM is decodable from the images at AUC 0.982
%   one centre (UM) is 100%% cases, so there centre and group are collinear
% For contrast, in proj_cfs scanner was orthogonal to group (r = 0.026) and
% stratification alone was sufficient.
%
% Note also that scaling does NOT help. TDT's 'z'/'all' is feature-wise: the
% same affine map per voxel across subjects, which cannot remove between-subject
% structure at all. Per-image z-scoring does remove the global mean and scale,
% but measured on discoverie that left centre decodability at 0.983 (from
% 0.982) - the site effect is spatial, not global.
%
% Three levers, which address different things and can be combined:

% (a) Restrict the sample. Cell array {column, values-to-keep}, e.g.
%     {'center', {'KUL'}} for a single-site analysis with no confound left to
%     control. Empty = use everyone.
subject_filter = {};

% (b) Residualize the features on nuisance variables before decoding. Named
%     phenotype columns are dummy-coded (a k-level factor becomes k-1 columns -
%     coding three sites as one -1/0/1 column treats them as ordered and
%     removes only one degree of freedom's worth of site variance) and
%     regressed out of the image matrix.
%     This is label-blind: labels never enter the transform, so it is applied
%     identically to the real and permuted runs and cannot leak group
%     information. Fitting it per training fold would be stricter still, but
%     TDT owns the CV loop and must not be modified, so that would mean calling
%     decoding() once per fold. Revisit if a result sits near threshold.
%     NOTE what this costs: where a nuisance level contains only one class, the
%     nuisance and the group effect are collinear and residualizing removes the
%     group signal with it.
nuisance_resid_vars = {};

% (b2) ComBat-harmonize the features on this variable before decoding.
%     Name of a phenotype column holding site/scanner labels, '' to switch off.
%     Harmonization runs with NO covariates (mod = []), deliberately and
%     unconditionally - see LaBGAScore_combat_fit for why that is structural
%     rather than a simplification.
%
%     WHY mod = [] IS NOT NEGOTIABLE HERE. Harmonizing with the outcome in mod
%     protects the group effect from removal, which sounds desirable and is
%     catastrophic: the labels then shape the features the classifier is
%     trained on. Simulated under H0 with no true group effect at all, using
%     this study's actual T2 geometry, KUL 101 (44 case / 57 control) and
%     UGOT 23 (18 / 5), i.e. 62/62 overall:
%
%       whole-sample, mod = group   AUC 0.547   above chance in 82% of sims
%       whole-sample, mod = []      AUC 0.448
%       fitted per training fold    AUC 0.472
%
%     Read that carefully, because only the first row is about validity.
%     mod = group pushes the estimate ABOVE chance on data with no effect in
%     it, so it is refused outright. With mod = [] the transform is label-blind
%     and cannot invent an effect, but its point estimate is still displaced -
%     here downwards - because the sites differ in class proportion (44% cases
%     at KUL against 78% at UGOT), so removing a site mean removes part of the
%     class contrast with it. Fitting per training fold reduces that
%     displacement (0.472 against 0.448) without eliminating it.
%
%     So treat the AUC from a harmonized run the way the residualized runs are
%     already treated: read the p-value and the distance from the reported null
%     mean, not the AUC on its own. LaBGAScore_combat_fit / _apply implement
%     the strict per-fold version, validated against combat.m to 2e-15, and are
%     the better choice where the point estimate itself has to be reported.
%
%     NOTE what this costs, as with residualization: a site whose subjects are
%     all one class has no within-site class contrast, so removing its site
%     effect removes its class signal too.
combat_batch_var = '';

% (b3) Reference site for ComBat: that site passes through unchanged and the
%     others are mapped onto it. '' harmonizes to the grand mean instead.
combat_ref = '';

% (c) Permute labels WITHIN levels of these variables when building the null.
%     This preserves each level's class counts, so the permuted classifier can
%     exploit the nuisance exactly as much as the real one, and the null lands
%     where the nuisance alone would put it rather than at chance. This fixes
%     the INFERENCE; it does not deflate the point estimate.
perm_within_vars = {};

% Variables to stratify the CV folds on, IN ADDITION to group. Folds are
% always balanced across groups; anything named here is balanced within group
% as well, so a nuisance variable cannot end up concentrated in a few folds.
% Typically the scanner or site. Set {} for group-only stratification.
%
% This is deliberately NOT the same as regressing the variable out. TDT has no
% covariate hook, and doing it per training fold means leaving TDT's CV loop.
% Stratification costs nothing and removes the failure mode that actually
% matters with a small nuisance stratum: a fold containing all or none of it.
cv_strata_vars = {};                  % e.g. {'PET_MR'}

% Seed for the fold assignment. The original script left this unset, so the
% real decoding used different folds on every run and was not reproducible.
cv_seed = 20260910;

% TDT SETTINGS

con2use = 'con_0003.nii';
conname = DSGN.contrastnames{sscanf(con2use, 'con_%d.nii')};
conname = strrep(conname, ' ', '_');
performance_metric = {'AUC_minus_chance'}; % script only tested with one metric
unbalanced = true;

analysis_mode = 'searchlight';    % 'searchlight' | 'roi' | 'wholebrain'

switch analysis_mode
    case 'searchlight'
        searchlight_radius = 6; % in mm
        mask_file = which('gm_mask_canlab2023_coarse_fmriprep20_0_20.nii');
        mask_obj = fmri_mask_image(mask_file);

        % TIMING BENCHMARK ONLY - leave empty for any real analysis.
        %
        % TDT's cfg.searchlight.subset is a LIST OF SEARCHLIGHT INDICES, not a
        % decimation factor: an Nx1 vector of indices into the searchlight mask
        % (NOT voxel indices of the whole volume), or an Nx3 matrix of XYZ
        % coordinates. See the cfg.searchlight.subset entry in decoding.m.
        %
        % Getting this wrong is expensive and quiet. Passing the scalar 20 does
        % not run every 20th centre - it runs ONE centre, the one at index 20,
        % and TDT reports no error because a 1x1 subset is a valid Nx1 list.
        % A benchmark built that way times a single searchlight and understates
        % a whole-brain run by orders of magnitude.
        %
        % To sample the mask evenly, pass indices, e.g.
        %     searchlight_subset = round(linspace(1, n_centres, 500))';
        % where n_centres is the number of voxels in mask_file.
        %
        % It must never be used for a result, and the guard below enforces
        % that. The reason is not merely that the map is sparse: TDT returns
        % 0, NOT NaN, for centres it did not run. Zero is a perfectly
        % legitimate value of AUC_minus_chance - it means exactly chance - so
        % the 'valid voxel' test further down (~isnan(real_vec)) cannot tell a
        % skipped voxel from a genuinely uninformative one. Every un-run centre
        % would enter the FDR correction and the TFCE null as real chance-level
        % data, deflating both. The failure is silent and the map looks fine.
        searchlight_subset = [];   % e.g. 8 = every 8th centre, benchmark only
    case 'roi'
        roi_list = {
                   which('aINS_L.nii')
                   which('aINS_R.nii')
                   which('Tha_L.nii')
                   which('Tha_R.nii')
                   which('Amyg_L.nii')
                   which('Amyg_R.nii')
                   which('IFG_vlPFC_L.nii')  
                   which('IFG_vlPFC_R.nii')
               }; % Add more ROI masks here - can be created with LaBGAS script
    case 'wholebrain'
        mask_file = which('gm_mask_canlab2023_coarse_fmriprep20_0_20.nii');
    otherwise
        error('analysis mode specified not implemented in TDT')
end

% PERMUTATION SETTINGS

% COMBINED-DESIGN PERMUTATIONS (speed)
%
% 0 keeps the original scheme: one decoding() call per permutation, parfor over
% permutations. Because TDT extracts the searchlight sphere and builds the
% kernel ONCE PER decoding() CALL, outside its own step loop, that scheme
% repeats the extraction and the kernel n_perms + 1 times for every one of the
% 150,630 centres, even though the features never change - only the labels do.
%
% Any value > 0 splits the permutations into that many chunks, gives each chunk
% a single design holding its permutations as SETS, and makes one decoding()
% call per chunk with cfg.results.setwise = 1. The sphere extraction and the
% kernel then happen once per centre per chunk instead of once per permutation,
% while parfor still runs the chunks in parallel.
%
%   -1  (default) AUTO: one chunk per parallel worker, resolved from the live
%       pool once it exists. This is the optimum and there is no reason to
%       depart from it - see below.
%    0  the original path, one decoding() call per permutation. Kept as the
%       reference implementation to validate the chunked path against.
%   >0  an explicit chunk count.
%
% WHY ONE CHUNK PER WORKER IS OPTIMAL, and why more is actively worse:
%   * parfor runs at most one chunk per worker at a time, so chunks beyond the
%     worker count queue into a second wave, a third, and so on.
%   * total extraction work is PROPORTIONAL TO THE CHUNK COUNT, because the
%     sphere extraction and kernel are paid once per chunk per centre. Extra
%     chunks are extra work, not merely extra scheduling.
%   Both costs are paid at once. proj_cfs ran a whole-GM searchlight with
%   perm_chunks = 105 on a 21-worker pool - 5 waves and 5x the extraction - and
%   it took 5.4 days. proj_moodbugs ran the same mask with 21 chunks on 21
%   workers, a single wave, in well under a day.
%   Fewer chunks than workers is the opposite error: idle workers.
%
% The arithmetic is identical either way - same designs, same labels, same
% classifier - so results must match the per-permutation path. Verify that on a
% small run before trusting a long one.
perm_chunks = -1;

n_perms = 1000;

% OUTPUT DIRECTORIES

% results_tag keeps variants of the same contrast and mode apart. Without it
% every sample restriction writes to the same folder and silently overwrites
% the last one - which happened here: three discoverie tiers all mapped to
% .../TDT/stress_vs_control/wholebrain.
if ~exist('results_tag','var'), results_tag = ''; end
if isempty(results_tag)
    tdt_resultsdir = fullfile(resultsdir,'TDT',conname,analysis_mode);
else
    tdt_resultsdir = fullfile(resultsdir,'TDT',conname,results_tag,analysis_mode);
end  % folder where all TDT results are saved, can work with subfolders if you want to run multiple analyses
    if ~exist(tdt_resultsdir,'dir')
        mkdir(tdt_resultsdir);
    end
    
% ATLAS SETTINGS
atlas = load_atlas('canlab2024');

% THRESHOLDS FOR OUTPUT FMRI_DATA OBJECTS
unc_p = 0.01;
fdr_p = 0.05;   % FDR-corrected p/q threshold for the output fmri_data objects
fwe_p = 0.05;   % TFCE FWE-corrected p threshold
%
% fdr_p and fwe_p were lost when the extent thresholds were split into the
% _auc/_tfce pairs below: the old block defined unc_p/unc_k/fdr_p/fdr_k/
% fwe_p/fwe_k together and the rewrite kept only unc_p. Nothing complained,
% because they are used ONLY in the searchlight branch - wholebrain and roi
% never reach thresholded_fmri_data_from_pval_nii. The cfs searchlight
% therefore ran the full 200 permutations, saved the null and both p-maps,
% and then died on "Unrecognized function or variable 'fdr_p'" 819 minutes in.
% Extent thresholds for the output fmri_data objects. Split into the plain AUC
% p-maps and the TFCE-derived maps, because an extent threshold means something
% different in each.
%
% On the AUC maps it is an ordinary display threshold: the map is voxelwise, so
% requiring a few contiguous voxels suppresses isolated specks.
%
% On the TFCE maps it corrects twice. TFCE already integrates cluster extent
% into the statistic, and the FWE map is already family-wise corrected across
% voxels, so a k on top removes signal that the correction has already accounted
% for. The same mistake in the second-level GLM stack was measured on
% proj_discoverie: k >= 50 removed every one of the 42 surviving TFCE-FWE voxels
% and reported an empty map. Hence 0 here, deliberately, not "not set".
unc_k_auc  = 50;
fdr_k_auc  = 25;

unc_k_tfce = 0;
fdr_k_tfce = 0;
fwe_k_tfce = 0;

    
%% ========================================================================
% 1. BUILD CV DESIGN
% ========================================================================

% The sample is restricted FIRST and the group codes validated afterwards, on
% the rows that remain. The other order made a label variable with a third
% level unusable: the "every row is pos or neg" check fired before
% subject_filter could drop that level, which is exactly what a within-group
% site check needs to do (decode centre A vs B among patients only).
table_combined = phenotype;

% ---- (a) restrict the sample ---------------------------------------------
if ~isempty(subject_filter)
    % Two accepted forms, matching prep_3a:
    %   {var, vals}                      one criterion
    %   {{var, vals}, {var, vals}, ...}  several, combined with AND
    % The second form is what a within-group site check needs - patients only
    % AND two centres only - which a single criterion cannot express.
    if iscell(subject_filter{1})
        filter_list = subject_filter;
    else
        filter_list = {subject_filter};
    end

    keep = true(height(table_combined),1);
    for fi = 1:numel(filter_list)
        filt_var = filter_list{fi}{1};
        filt_val = filter_list{fi}{2};
        if ~iscell(filt_val), filt_val = num2cell(filt_val); end
        if ~ismember(filt_var, table_combined.Properties.VariableNames)
            error('\nsubject_filter names ''%s'', which is not a column of the phenotype file.\n', filt_var);
        end
        fv = table_combined.(filt_var);
        if isnumeric(fv)
            keep_i = ismember(fv, cell2mat(filt_val(:)'));
        else
            if ~iscell(fv), fv = cellstr(string(fv)); end
            keep_i = ismember(fv, cellfun(@(x) char(string(x)), filt_val, 'UniformOutput', false));
        end
        valstr = strjoin(cellfun(@(x) char(string(x)), filt_val, 'UniformOutput', false), ',');
        fprintf('\nsubject_filter: %s = %s keeps %d of %d\n', ...
            filt_var, valstr, sum(keep_i), numel(keep_i));
        keep = keep & keep_i;
    end

    if ~any(keep)
        error('\nsubject_filter left 0 subjects.\n');
    end
    fprintf('subject_filter: %d of %d subjects kept after all criteria\n', sum(keep), numel(keep));
    table_combined = table_combined(keep,:);
end

% Group membership, using the configured column and codes, on the RETAINED rows.
grp_raw = table_combined.(pheno_group_var);
if iscell(grp_raw) || isstring(grp_raw), grp_raw = double(string(grp_raw)); else, grp_raw = double(grp_raw); end

is_pos = grp_raw == group_pos_code;
is_neg = grp_raw == group_neg_code;

if ~all(is_pos | is_neg)
    error(['%d of %d retained rows in %s are neither group_pos_code (%g) nor group_neg_code (%g).\n' ...
           'Check pheno_group_var, the two codes, and whether subject_filter drops the other level(s).'], ...
           sum(~(is_pos|is_neg)), numel(grp_raw), pheno_group_var, group_pos_code, group_neg_code);
end

table_combined.labels = zeros(height(table_combined),1);
table_combined.labels(is_pos) = 1;
table_combined.labels(is_neg) = -1;

fprintf('\n%s (label +1): n = %d\n%s (label -1): n = %d\n', ...
    group_pos_name, sum(is_pos), group_neg_name, sum(is_neg));

% ---- how much can the nuisance alone do? ---------------------------------
% Printed BEFORE any decoding, because it is the number the result has to beat.
% A classifier that learns nothing but the nuisance gets this for free.
benchmark_vars = unique([nuisance_resid_vars(:); perm_within_vars(:); cv_strata_vars(:)], 'stable');
if ~isempty(benchmark_vars)
    yb = double(table_combined.labels(:) == 1);
    for bv = benchmark_vars'
        if ~ismember(bv{1}, table_combined.Properties.VariableNames), continue, end
        [Xb, ~, catb] = LaBGAScore_dummy_code(table_combined.(bv{1}));
        if isempty(Xb) || rank([ones(size(Xb,1),1) Xb]) < 2, continue, end
        mb = fitglm(Xb, yb, 'Distribution', 'binomial');
        [~,~,~,ab] = perfcurve(yb, predict(mb, Xb), 1);
        [~, ~, pb] = crosstab(double(catb), yb);
        fprintf(['  BENCHMARK: ''%s'' alone predicts group at AUC %.3f (in-sample), ' ...
                 'chi2 p = %.3g\n'], bv{1}, ab, pb);
        if ab > 0.6
            fprintf(['             ^ that is a real confound. Stratifying folds does NOT remove it; ' ...
                     'use nuisance_resid_vars and/or perm_within_vars.\n']);
        end
    end
end

% ---- stratified fold assignment ------------------------------------------
%
% Folds are balanced across groups, and across any variable named in
% cv_strata_vars within each group.
%
% Assignment is round-robin over a random permutation of each stratum, not
% cvpartition. cvpartition(n,'KFold',K) requires n >= K and so fails outright
% on a small stratum - with 3 subjects on one scanner and K = 5 it cannot be
% used at all - whereas round-robin spreads any stratum, however small, as
% evenly as it can be spread. The starting fold is randomised per stratum so
% small strata do not all pile into folds 1..n.

rng(cv_seed, 'twister');   % reproducible folds; the original script left this unset

strata_key = strings(height(table_combined),1);
for i = 1:height(table_combined)
    key = sprintf('g%d', table_combined.labels(i));
    for v = 1:numel(cv_strata_vars)
        val = table_combined.(cv_strata_vars{v})(i);
        if iscell(val), val = val{1}; end
        key = sprintf('%s|%s=%s', key, cv_strata_vars{v}, string(val));
    end
    strata_key(i) = key;
end

table_combined.chunks = zeros(height(table_combined),1);
ustrata = unique(strata_key);

for u = 1:numel(ustrata)
    idx  = find(strata_key == ustrata(u));
    perm = idx(randperm(numel(idx)));
    off  = randi(K) - 1;
    table_combined.chunks(perm) = mod((0:numel(perm)-1) + off, K) + 1;
end

table_combined.id = (1:height(table_combined))';

% ---- report the resulting balance, so it is visible rather than assumed ----
fprintf('\nfold composition (K = %d, seed %d):\n', K, cv_seed);
fprintf('  %-6s %8s %8s', 'fold', group_pos_name, group_neg_name);
for v = 1:numel(cv_strata_vars), fprintf(' %14s', cv_strata_vars{v}); end
fprintf('\n');
for k = 1:K
    in_k = table_combined.chunks == k;
    fprintf('  %-6d %8d %8d', k, sum(in_k & table_combined.labels==1), sum(in_k & table_combined.labels==-1));
    for v = 1:numel(cv_strata_vars)
        vals = table_combined.(cv_strata_vars{v})(in_k);
        if iscell(vals), vals = double(string(vals)); else, vals = double(vals); end
        fprintf(' %14s', sprintf('%d/%d', sum(vals>0), numel(vals)));
    end
    fprintf('\n');
end

if any(accumarray(table_combined.chunks, table_combined.labels==1) == 0) || ...
   any(accumarray(table_combined.chunks, table_combined.labels==-1) == 0)
    error('at least one fold contains no subjects from one of the groups; lower K');
end



%% ========================================================================
% 2. BUILD TDT CONFIGURATION (Mode‑Adaptive) - EDIT THESE
% ========================================================================

cfg = decoding_defaults;
cfg.results.dir = tdt_resultsdir;

% Allow reruns. TDT defaults cfg.results.overwrite to 0 and then ERRORS if a
% result file is already there, so without this every rerun of this script dies
% - and it dies after loading the data and running the true decoding, not at
% the start. Reruns are the normal case here (a changed fold seed, a different
% contrast, a fixed bug), and the results directory is scoped per model,
% contrast and analysis mode, so overwriting it is what is wanted. It is
% announced rather than silent, because the previous run's maps do disappear.
cfg.results.overwrite = 1;
if exist(fullfile(tdt_resultsdir, ['res_' performance_metric{1} '.mat']), 'file')
    fprintf('\n  NOTE: overwriting previous results in %s\n', tdt_resultsdir);
end

% Set for every mode: only the searchlight branch can turn it on, but the
% guard before the inference section reads it unconditionally.
benchmark_only = false;

switch lower(analysis_mode)

   case 'searchlight'
       cfg.analysis = 'searchlight';
       cfg.searchlight.unit = 'mm';
       cfg.searchlight.radius = searchlight_radius;
       cfg.searchlight.spherical = 1;
       cfg.files.mask = mask_file;
       if ~isempty(searchlight_subset)
           % Benchmark path. Refuse to go on to inference: see the comment at
           % searchlight_subset for why un-run centres cannot be detected later.
           cfg.searchlight.subset = searchlight_subset;
           benchmark_only = true;
           warning('LaBGAScore:decoding:benchmarkSubset', ...
               ['searchlight_subset = %d: TIMING BENCHMARK ONLY. Centres are ' ...
                'decimated and un-run centres return 0 (chance), not NaN, so no ' ...
                'valid p-map, FDR or TFCE can be produced. Inference will be skipped.'], ...
                searchlight_subset);
       else
           benchmark_only = false;
       end
       fprintf('>> RUNNING SEARCHLIGHT\n');

   case 'roi'
       cfg.analysis = 'ROI';
       cfg.files.mask = roi_list;
       fprintf('>> RUNNING ROI DECODING\n');

   case 'wholebrain'
       cfg.analysis = 'wholebrain';
       cfg.files.mask = mask_file;
       fprintf('>> RUNNING WHOLE‑BRAIN DECODING\n');

   otherwise
       error('Unknown analysis mode.');
end

% Load subject images
%
% scaled_contrast_dir, when set, points at SECOND-LEVEL contrast images written
% by LaBGAScore_export_scaled_contrasts - one <subjectID>.nii per subject, built
% from z-scored (and where applicable ComBat-harmonised) condition images: the
% features the GLM and the PDM analyse.
%
% Empty reproduces the original behaviour, first-level con images from datadir.
% That is NOT equivalent - those are RAW contrasts, so the SVM would answer the
% same question on a different feature space from every other analysis in the
% model. Set it whenever the model's GLM uses myscaling_glm other than 'raw'.
if ~exist('scaled_contrast_dir','var'), scaled_contrast_dir = ''; end
cfg.files.name = cell(height(table_combined),1);
if isempty(scaled_contrast_dir)
    fprintf('\nfeatures: FIRST-LEVEL %s from %s\n', con2use, datadir);
    for i = 1:height(table_combined)
        cfg.files.name{i} = sprintf(['%s/%s/' con2use], ...
            datadir, table_combined.(pheno_id_var){i});
    end
else
    % Export on demand rather than requiring a separate script to have been run
    % first. The images are a deterministic function of the contrast objects, so
    % there is nothing to be gained by making the user remember an ordering
    % dependency - and everything to lose if they forget, because the fallback
    % is to silently decode raw FIRST-LEVEL images, which are a different
    % quantity from what the GLM analysed.
    %
    % export_conidx  which contrast to export (defaults to the decoded contrast)
    % export_object  which contrast object: 'DATA_OBJ_CON' matches a GLM run with
    %                myscaling_glm = 'raw', 'DATA_OBJ_CONsc' one run on z-scored
    %                conditions, 'DATA_OBJ_CONscc' l2norm-scaled contrasts.
    if ~exist('export_conidx','var') || isempty(export_conidx)
        if exist('con2use','var') && isnumeric(con2use) && isscalar(con2use)
            export_conidx = con2use;
        else
            export_conidx = 1;
        end
    end
    if ~exist('export_object','var') || isempty(export_object)
        if exist('myscaling_glm','var') && strcmp(myscaling_glm,'scaled')
            export_object = 'DATA_OBJ_CONsc';
        else
            export_object = 'DATA_OBJ_CON';
        end
    end

    n_exported = 0;
    if exist(scaled_contrast_dir,'dir')
        n_exported = numel(dir(fullfile(scaled_contrast_dir,'*.nii')));
    end
    % Name the contrast being exported, not just its number. The index comes from
    % a guarded default that silently falls back to 1 when con2use is a filename
    % string - which it always is - so the number alone gives the reader nothing
    % to check against. The name makes a mismatch with the intended analysis
    % obvious in the report.
    % DAT is NOT in this script's workspace: the decoding chain never loads
    % image_names_and_setup.mat, so exist('DAT','var') was false on every run
    % and the name below always printed '<name unavailable>' - the block never
    % once did the job it exists for. Look it up instead.
    if ~exist('DAT','var') && exist(fullfile(resultsdir,'image_names_and_setup.mat'),'file')
        S_conname = load(fullfile(resultsdir,'image_names_and_setup.mat'),'DAT');
        if isfield(S_conname,'DAT'), DAT = S_conname.DAT; end
        clear S_conname
    end
    if exist('DAT','var') && isfield(DAT,'contrastnames') && ...
            export_conidx >= 1 && export_conidx <= numel(DAT.contrastnames)
        export_conname = DAT.contrastnames{export_conidx};
    else
        export_conname = '<name unavailable>';
    end

    if n_exported == 0
        fprintf(['\nno exported contrasts found in %s\n' ...
                 '  exporting SECOND-LEVEL contrast %d (%s) from %s now\n'], ...
                 scaled_contrast_dir, export_conidx, export_conname, export_object);
        % contrast_objects_tag picks which harmonisation path to decode when a model
        % holds more than one. Where the GLM path is ComBat'd with mod = {'group'},
        % its images carry a term proportional to each subject's own label and are
        % NOT valid classifier features - point this at the label-blind path instead.
        if ~exist('contrast_objects_tag','var') || isempty(contrast_objects_tag)
            contrast_objects_tag = '';
        end
        scaled_contrast_dir = LaBGAScore_export_scaled_contrasts(resultsdir, ...
            export_conidx, scaled_contrast_dir, 'object', export_object, ...
            'tag', contrast_objects_tag);
    end
    fprintf('\nfeatures: SECOND-LEVEL contrast %d (%s), scaled contrasts from %s\n', ...
            export_conidx, export_conname, scaled_contrast_dir);
    for i = 1:height(table_combined)
        fn = fullfile(scaled_contrast_dir, [table_combined.(pheno_id_var){i} '.nii']);
        if ~exist(fn,'file')
            error('\nno exported contrast for %s at %s\n', table_combined.(pheno_id_var){i}, fn);
        end
        cfg.files.name{i} = fn;
    end
end

cfg.files.chunk = table_combined.chunks;

% labels are already set in section 1 from pheno_group_var and the two group
% codes. They used to be re-derived here from a hardcoded 'patient' column,
% which (a) does not exist outside the study this was written for and (b) tested
% patient==1 / patient==-1 while the fold split above used patient==0 / ==1, so
% one class would have kept the label 0 rather than -1.
cfg.files.label = table_combined.labels;

cfg.results.output = performance_metric;
cfg.verbose = 0;

% ---- classifier and scaling ----------------------------------------------
%
% Defined ONCE and applied to the real run and the permutations alike, because
% they have to be the same procedure. An earlier version of this script set
% them separately and they diverged: the real statistic came from a C-SVC
% while the null was generated with '-s 2', which is ONE-CLASS SVM in libsvm
% (svm.h: enum {C_SVC, NU_SVC, ONE_CLASS, EPSILON_SVR, NU_SVR}) - a model that
% never sees the training labels. A null from a different procedure is not the
% null distribution of the real statistic, so the p-values built on it were
% invalid. It also set cfg.decoding_method, which is not a TDT field at all
% (the field is cfg.decoding.method) and so did nothing.
%
% TWO VALID COMBINATIONS. They differ in speed, not really in validity:
%
%   'kernel'  classification_kernel + scaling estimated on all data.
%             TDT precomputes the kernel once per decoding, which is a large
%             saving when voxels >> subjects - decisive for wholebrain and
%             worthwhile for searchlight over many permutations. TDT itself
%             recommends estimating scaling on all samples, on the grounds
%             that a simple rescaling carries no category information from
%             training to test (see decoding_scale_data.m).
%
%   'strict'  classification + 'across' scaling, i.e. scaling parameters
%             estimated on the training fold only and applied to the test
%             fold. Removes even that much dependence on the test data, at
%             the cost of the kernel speed-up: 'across' CANNOT be combined
%             with classification_kernel, because under the kernel path
%             data_train is a struct holding kernel(i_train,i_train) (see
%             tdt_get_train_test in decoding.m) and TDT's per-fold scaling
%             would be applied to that kernel matrix rather than to the
%             features. TDT does not guard against this.
%
% WHY 'z' AND NOT 'min0max1'. Both scale per voxel, but they are set by very
% different things: 'z' uses the mean and SD over all subjects, 'min0max1' uses
% only the two most extreme subjects at that voxel (TDT computes
% min(data,[],1)/max(data,[],1), i.e. per feature). Measured on proj_cfs
% con_0003, 134 subjects over 150,630 grey-matter voxels:
%
%   range / SD per voxel      median 6.51, p95 8.85  (Gaussian expectation ~5.5)
%   dropping ONE subject at    median 19.8%, p95 45.7%, max 78.8%
%     each end shrinks range by
%   voxels where some subject  12.3%
%     exceeds |z| > 5
%
% So at a typical voxel a single subject at each end sets a fifth of the range
% that defines the scaling, and at the 95th percentile nearly half of it.
% min0max1 maps exactly those two subjects to 0 and 1 and compresses everyone
% else into what is left, which makes the scaling of every voxel depend on its
% least reliable observations.
%
% Note 'min0max1global' is a different thing again, and is the one TDT actually
% recommends for libsvm: one global min/max, a pure speed device that
% "produces the same classification results as for unscaled data". It is not a
% normalisation choice. 'min0max1' gives the fragility of order statistics
% without that guarantee, and is easy to select by conflating the two names.
%
% 'kernel' is the default because searchlight runtime is the binding
% constraint here. Switch to 'strict' if you want train-only scaling and can
% afford it.
scaling_regime = 'kernel';    % 'kernel' | 'strict'
                              % 'kernel' is TDT's own recommended estimation = 'all': label-blind
                              % scaling cannot carry category information across the train/test
                              % split, and the precomputed kernel is reused across permutations.
                              % 'strict' ('across') re-derives the linear kernel on every fold of
                              % every permutation - measured 12-25x slower on a whole-brain run.

switch scaling_regime
    case 'kernel'
        decoding_method  = 'classification_kernel';
        model_parameters = '-s 0 -t 4 -c 1 -b 0 -q';   % C-SVC, precomputed kernel
        scale_method     = 'z';
        scale_estimation = 'all';
    case 'strict'
        decoding_method  = 'classification';
        model_parameters = '-s 0 -t 0 -c 1 -b 0 -q';   % C-SVC, linear kernel
        scale_method     = 'z';
        scale_estimation = 'across';
    otherwise
        error('scaling_regime must be ''kernel'' or ''strict''');
end

cfg.decoding.method = decoding_method;
cfg.decoding.train.(decoding_method).model_parameters = model_parameters;
cfg.scale.method     = scale_method;
cfg.scale.estimation = scale_estimation;

fprintf('\ndecoding: %s, scaling %s/%s (regime ''%s'')\n', ...
    decoding_method, scale_method, scale_estimation, scaling_regime);

cfg.plot_selected_voxels = 0;

cfg.design = make_design_cv(cfg);
if unbalanced
    cfg.design.unbalanced_data = 'ok';
end


%% ========================================================================
% 3. RUN TRUE DECODING
% ========================================================================

fprintf('\n=== RUNNING TRUE DECODING ===\n');
% Capture passed_data and misc as well as the results. TDT's signature is
%   [results, cfg, passed_data, misc] = decoding(cfg, passed_data, misc)
% and handing both straight back into every permutation skips reloading the
% images AND recomputing the searchlight neighbourhoods, which is where the
% permutation loop previously spent nearly all of its time: it called
% decoding(cfgPi) with only a cfg, so each of n_perms runs re-read every
% subject's image from disk and rebuilt the searchlight index from scratch.
t_real = tic;
[results, cfg, passed_data, misc] = decoding(cfg);

feats_modified = false;

% ---- (a2) ComBat-harmonize the features on site ---------------------------
%
% Same placement and the same argument as the residualization below: applied to
% the feature matrix TDT has already assembled, before any decoding, so the real
% run and every permutation see identical features. mod is empty, so nothing
% about the labels enters the transform.
if ~isempty(combat_batch_var)

    if isempty(which('combat'))
        error('combat_batch_var is set but combat.m is not on the path. Add ComBatHarmonization/Matlab/scripts.');
    end
    if ~ismember(combat_batch_var, table_combined.Properties.VariableNames)
        error('\ncombat_batch_var names ''%s'', not a column of the phenotype file.\n', combat_batch_var);
    end

    batch_raw = table_combined.(combat_batch_var);
    batch_lbl = cellstr(string(batch_raw(:)));
    [batch_names, ~, batch_idx] = unique(batch_lbl, 'stable');
    batch_idx = double(batch_idx);

    fprintf('\n=== COMBAT HARMONIZATION ON %s (mod = [], label-blind) ===\n', upper(combat_batch_var));

    dat_field_cb = '';
    for cand = {'data','dat','samples'}
        if isfield(passed_data, cand{1}), dat_field_cb = cand{1}; break, end
    end
    if isempty(dat_field_cb)
        error('\ncannot find the data matrix in passed_data (fields: %s)\n', ...
            strjoin(fieldnames(passed_data)', ', '));
    end

    Ycb = double(passed_data.(dat_field_cb));          % samples x features
    if size(Ycb,1) ~= numel(batch_idx)
        error('\npassed_data has %d rows but %s has %d entries.\n', ...
            size(Ycb,1), combat_batch_var, numel(batch_idx));
    end

    for b = 1:numel(batch_names)
        sel = batch_idx == b;
        cls = unique(cfg.files.label(sel));
        fprintf('  %-12s n = %3d   classes present: %s\n', batch_names{b}, sum(sel), mat2str(cls(:)'));
        if numel(cls) < 2
            fprintf(['        NOTE: one class only - this site has no within-site class\n' ...
                     '        contrast, so harmonizing it removes its class signal too.\n']);
        end
    end

    ref_code_cb = [];
    if ~isempty(combat_ref)
        ref_code_cb = find(strcmp(batch_names, char(string(combat_ref))));
        if isempty(ref_code_cb)
            error('\ncombat_ref ''%s'' is not one of the sites present (%s).\n', ...
                char(string(combat_ref)), strjoin(batch_names(:)', ', '));
        end
        fprintf('  reference site: %s (passes through unchanged)\n', batch_names{ref_code_cb});
    else
        fprintf('  no reference site: harmonizing to the grand mean\n');
    end

    % combat.m refuses features that are constant across samples, and a feature
    % that is constant WITHIN a site drives that site's variance estimate to zero,
    % which yields NaN/Inf silently instead of erroring. So harmonise only the
    % features that are safe on both counts. Constant features carry no
    % information by construction, so passing them through untouched changes
    % nothing the classifier could have used. On a whole-brain GM mask this is
    % typically a small number of edge voxels that are zero in every image.
    sd_all_cb = std(Ycb, 0, 1);
    sd_min_cb = inf(1, size(Ycb, 2));
    for b = 1:numel(batch_names)
        sd_min_cb = min(sd_min_cb, std(Ycb(batch_idx == b, :), 0, 1));
    end
    cb_ok = sd_all_cb > 0 & sd_min_cb > 0;
    if ~any(cb_ok)
        error('\nevery feature is constant across samples; nothing to harmonize.\n');
    end
    if ~all(cb_ok)
        fprintf(['  %d of %d features constant (globally or within a site):\n' ...
                 '        passed through UNHARMONIZED, they carry no information\n'], ...
                 sum(~cb_ok), numel(cb_ok));
    end

    % combat.m wants p x n; passed_data is n x p
    cb_args = {Ycb(:, cb_ok)', batch_idx, [], 1};
    if ~isempty(ref_code_cb), cb_args = [cb_args {'ref', ref_code_cb}]; end %#ok<AGROW>
    var_before_cb = mean(var(Ycb(:, cb_ok), 0, 1));
    Ycb(:, cb_ok) = combat(cb_args{:})';
    var_after_cb = mean(var(Ycb(:, cb_ok), 0, 1));
    passed_data.(dat_field_cb) = Ycb;
    feats_modified = true;

    fprintf('  mean feature variance %.4g -> %.4g\n', var_before_cb, var_after_cb);

end

% ---- (b) residualize features on the nuisance variables -------------------
%
% Done on the feature matrix TDT has already assembled, before any decoding, so
% the real run and every permutation see identical features. The transform is
% LABEL-BLIND - only nuisance columns enter it - which is what makes it safe to
% fit once on all subjects rather than per training fold: no group information
% can leak through it, and the permutation null passes through the same
% transform. Fitting per training fold would be stricter, but TDT owns the CV
% loop and is not to be modified.
if ~isempty(nuisance_resid_vars)
    Xn = [];
    for nv = nuisance_resid_vars(:)'
        if ~ismember(nv{1}, table_combined.Properties.VariableNames)
            error('\nnuisance_resid_vars names ''%s'', not a column of the phenotype file.\n', nv{1});
        end
        Xn = [Xn LaBGAScore_dummy_code(table_combined.(nv{1}))]; %#ok<AGROW>
    end
    Xn = [ones(size(Xn,1),1) Xn];

    fprintf('\n=== RESIDUALIZING FEATURES ON %s (%d dummy column(s)) ===\n', ...
        upper(strjoin(nuisance_resid_vars, ', ')), size(Xn,2)-1);

    dat_field = '';
    for cand = {'data','dat','samples'}
        if isfield(passed_data, cand{1}), dat_field = cand{1}; break, end
    end
    if isempty(dat_field)
        error('\ncannot find the data matrix in passed_data (fields: %s)\n', ...
            strjoin(fieldnames(passed_data)', ', '));
    end

    Ydat = double(passed_data.(dat_field));       % samples x features
    if size(Ydat,1) ~= size(Xn,1)
        error('\npassed_data has %d rows but the design has %d subjects.\n', size(Ydat,1), size(Xn,1));
    end
    var_before = mean(var(Ydat, 0, 1));
    Ydat = Ydat - Xn*(Xn\Ydat);                   % keep residuals
    var_after = mean(var(Ydat, 0, 1));
    passed_data.(dat_field) = Ydat;

    fprintf('  mean feature variance %.4g -> %.4g (%.1f%% removed)\n', ...
        var_before, var_after, 100*(1-var_after/var_before));
    fprintf(['  NOTE: where a nuisance level holds only one class, nuisance and group are\n' ...
             '        collinear and the group signal goes with it.\n']);

    feats_modified = true;
end

% One re-run covers both transforms: whichever of ComBat and residualization
% ran, the decoding below sees the final feature matrix.
if feats_modified
    [results, cfg, passed_data, misc] = decoding(cfg, passed_data, misc);
end

t_real = toc(t_real);
fprintf('  true decoding took %.1f s\n', t_real);

% Extract vector format of real results
outname = cfg.results.output{1};
real_vec = results.(outname).output(:);


%% ========================================================================
% 4. GENERATE PERMUTATION DESIGNS
% ========================================================================

cfgp = rmfield(cfg,'design');
cfgp.design.function.name = 'make_design_cv';
% The permutation designs must come from the same procedure as the real run.
% This block previously switched the classifier and the scaling here, which is
% how the real statistic and its null came to be computed differently.
cfgp.decoding.method = decoding_method;
cfgp.decoding.train.(decoding_method).model_parameters = model_parameters;
cfgp.scale.method = scale_method;
cfgp.scale.estimation = scale_estimation;

% Seed the permutations. Without this make_design_permutation draws from
% whatever state the RNG happens to be in, so the null - and therefore every
% p-value - differs between runs of the same script and cannot be regenerated.
% cv_seed + 2 keeps it distinct from the fold assignment (cv_seed) and the
% restricted-permutation relabelling (cv_seed + 1).
rng(cv_seed + 2, 'twister');

designs = make_design_permutation(cfgp, n_perms, 0);

% ---- (c) restrict the permutation to within levels of the nuisance --------
%
% make_design_permutation shuffles labels freely, so the null is "what if group
% were unrelated to anything", and the null AUC sits at chance. When a nuisance
% predicts group that is the wrong reference: the real classifier can exploit
% the nuisance and the null classifier cannot, so the nuisance's contribution
% is scored as if it were signal.
%
% Permuting WITHIN levels keeps each level's class counts exactly as observed,
% so a permuted classifier can exploit the nuisance just as much as the real
% one. The null then lands where the nuisance alone puts it (in discoverie,
% near AUC 0.745 rather than 0.5) and the p-value asks the question that
% matters: does this beat what site structure alone would give?
%
% A level holding a single class contributes no permutability - permuting
% within it is the identity - so the label contrast comes from the mixed
% levels only. That is a property of the data, not a bug: where a level is
% all-cases, nothing can separate group from site there.
if ~isempty(perm_within_vars)
    strata_perm = zeros(height(table_combined),1);
    for pv = perm_within_vars(:)'
        if ~ismember(pv{1}, table_combined.Properties.VariableNames)
            error('\nperm_within_vars names ''%s'', not a column of the phenotype file.\n', pv{1});
        end
        [~, ~, cvp] = LaBGAScore_dummy_code(table_combined.(pv{1}));
        strata_perm = strata_perm * 1000 + double(cvp(:));
    end

    % Cross with the CV fold. This is not optional, and leaving it out is a
    % silent, serious error.
    %
    % TDT permutes WITHIN CHUNK by default (cfg.permute.exchangeable = 0),
    % which preserves each fold's class counts exactly. That is deliberate: if
    % a test fold ends up enriched in one class, the training folds are
    % depleted in it, the classifier is biased against the test fold's majority
    % class, and cross-validated performance drops BELOW chance. Preserving the
    % per-fold counts removes that anti-correlation.
    %
    % Permuting within the nuisance level alone throws that away. Measured on
    % discoverie T2 (n = 124, 1000 permutations), the AUC-minus-chance null:
    %     free permutation (TDT, within chunk) : mean  -0.20, sd 6.92
    %     within centre only                   : mean -10.24, sd 4.89
    % A null centred 10 points below chance makes every observed value look
    % good and the p-value meaningless.
    %
    % Crossing centre with chunk preserves BOTH: each centre keeps its
    % case/control counts (so the nuisance stays exploitable in the null, which
    % is the point) and each fold keeps its class counts (so no anti-learning).
    strata_perm = strata_perm * 1000 + double(table_combined.chunks(:));

    ustr = unique(strata_perm);

    fprintf('\n=== RESTRICTING PERMUTATION TO WITHIN %s ===\n', upper(strjoin(perm_within_vars, ', ')));
    for u = ustr'
        sel = strata_perm == u;
        npos = sum(table_combined.labels(sel) ==  1);
        nneg = sum(table_combined.labels(sel) == -1);
        fprintf('  stratum %g: n = %3d (%d vs %d)\n', u, sum(sel), npos, nneg);
        if ~(npos > 0 && nneg > 0)
            fprintf('             ^ single class, contributes no permutability\n');
        end
        if sum(sel) < 4
            fprintf('             ^ only %d subject(s): crossing nuisance with fold makes cells small\n', sum(sel));
        end
    end

    labels_obs = table_combined.labels(:);
    rng(cv_seed + 1, 'twister');
    for pidx = 1:numel(designs)
        newlab = labels_obs;
        for u = ustr'
            sel = find(strata_perm == u);
            newlab(sel) = labels_obs(sel(randperm(numel(sel))));
        end
        % write the permuted labels into every CV step of this design
        for stp = 1:size(designs{pidx}.label, 2)
            designs{pidx}.label(:, stp) = newlab;
        end
    end
    fprintf('  %d permutation designs rebuilt within stratum\n', numel(designs));
end


%% ========================================================================
% 5. FAST PERMUTATION DECODING (NO FOLDERS, IN‑MEMORY)
% ========================================================================

fprintf('\n=== RUNNING %d PERMUTATIONS WITHOUT WRITING FILES ===\n', n_perms);

% Start pool if needed
LaBGAScore_smart_parallel_pool_setup

% Resolve perm_chunks = -1 (AUTO) to exactly one chunk per worker. Done here
% because the pool does not exist before this line. One wave, every worker busy,
% and the minimum extraction cost consistent with using the whole pool - see the
% option documentation above for why more chunks is worse on both counts.
if exist('perm_chunks','var') && perm_chunks < 0
    % Prefer the LIVE pool: it is what parfor will actually use, which can differ
    % from what was requested. LaBGAScore_smart_parallel_pool_setup is a SCRIPT,
    % so it leaves nWorkers behind in this workspace - a sound second source.
    % Do NOT use its `pool` variable: that was captured BEFORE parpool and is
    % stale whenever the pool was created or resized.
    pool_now = gcp('nocreate');
    if ~isempty(pool_now)
        perm_chunks = pool_now.NumWorkers;
        chunk_src = 'live pool';
    elseif exist('nWorkers','var') && ~isempty(nWorkers) && nWorkers >= 1
        perm_chunks = nWorkers;
        chunk_src = 'nWorkers from the pool setup';
    else
        perm_chunks = 1;
        chunk_src = 'fallback, no pool found';
        warning(['perm_chunks = -1 (auto) but no parallel pool exists; ' ...
                 'falling back to a single chunk.']);
    end
    fprintf('  perm_chunks auto-set to %d (%s): one chunk per worker, single wave\n', ...
            perm_chunks, chunk_src);
end


Cdesigns    = parallel.pool.Constant(designs);

% Share the loaded data and the searchlight neighbourhoods across workers.
% parallel.pool.Constant sends each ONCE per worker; without it parfor would
% broadcast both on every iteration, which for a searchlight is hundreds of MB
% per permutation.
Cpassed     = parallel.pool.Constant(passed_data);
Cmisc       = parallel.pool.Constant(misc);

% Build template cfg from the REAL cfg, so the permutations cannot drift away
% from the procedure that produced the real statistic. Only the design changes.
cfg_template = cfg;
cfg_template.results.write = 0;      % no folders, no NIfTIs, in memory only
cfg_template.verbose       = 0;
cfg_template.plot_selected_voxels = 0;
cfg_template.design        = [];

% Preallocate null matrix
V = numel(real_vec);
all_perm_results = zeros(V, n_perms, 'single');

% Progress
tracker = ProgressTracker(n_perms);
q = parallel.pool.DataQueue;
afterEach(q, @(~) tracker.update());

fprintf('Running %d permutations (%s, scaling %s, %s)...\n', ...
    n_perms, decoding_method, scale_estimation, analysis_mode);

% HEARTBEAT: progress visible while the run is still going.
%
% publish() buffers a script's stdout until the script ENDS, so a long
% searchlight shows nothing at all until it finishes - the 819-minute cfs run
% was completely opaque, and a stalled run was indistinguishable from a slow
% one. Each worker appends one line per permutation to this file, which is
% written straight to disk and so is readable from outside while the run is
% in flight. Cheap: one short append per permutation.
hb_file = fullfile(tdt_resultsdir, 'progress_heartbeat.txt');
if exist(hb_file,'file') == 2, delete(hb_file); end
hb_t0 = datestr(now, 'yyyy-mm-dd HH:MM:SS');
fid_hb = fopen(hb_file,'w');
if fid_hb > 0
    fprintf(fid_hb, 'start %s | n_perms %d | mode %s | chunks %d\n', hb_t0, n_perms, analysis_mode, perm_chunks);
    fclose(fid_hb);
end
t_perm = tic;

% The groups are of unequal size (that is the design, not a mistake), so TDT
% warns about unbalanced training folds on every call. Inside the permutation
% loop that fires twice per permutation - once per design column - and each
% warning drags a six-line parfor stack trace with it. At 1000 permutations
% that was 12,000 of the 17,000 lines in the published report, burying the
% actual results. TDT resets its own warning counter on each decoding() call,
% so its "switched off after the second time" mechanism never engages here.
%
% Silencing it on the workers is the only lever available without editing TDT.
% It does NOT suppress warningv's companion fprintf, which is a plain fprintf
% rather than a warning, so roughly one line per permutation still gets
% through. Note this only hides an expected warning: the imbalance is real,
% and AUC is used precisely because it is insensitive to class prevalence.
warning('off', 'DECODING:CheckUnbalancedDataOk');
parfevalOnAll(@() warning('off', 'DECODING:CheckUnbalancedDataOk'), 0);

if perm_chunks <= 0

    % ORIGINAL PATH: one decoding() call per permutation, parfor over permutations.
    parfor p = 1:n_perms
       cfgPi = cfg_template;
       cfgPi.design = Cdesigns.Value{p};
       cfgPi.design.unbalanced_data = 'ok';
       r = decoding(cfgPi, Cpassed.Value, Cmisc.Value);
       all_perm_results(:,p) = single(r.(outname).output(:));
       fid_w = fopen(hb_file,'a');
       if fid_w > 0, fprintf(fid_w,'perm %d %s\n', p, datestr(now,'HH:MM:SS')); fclose(fid_w); end
       send(q,1);
    end

else

    % COMBINED-DESIGN PATH: one call per CHUNK, permutations carried as sets.
    %
    % TDT's decoding loop is
    %     for i_decoding (searchlight centre)
    %         current_data = <extract sphere>          % once per call
    %         kernel = kernel_function(current_data)   % once per call
    %         for i_step (design column)
    %             train / test using cfg.design.label(:,i_step)
    % so everything before the step loop is repeated for every decoding() call.
    % Putting several permutations into ONE design as sets turns them into extra
    % step columns, which means the extraction and the kernel are paid once per
    % centre per chunk rather than once per centre per permutation. The features
    % are identical across permutations - only labels change - so this is pure
    % saving, not an approximation.
    chunk_edges = round(linspace(0, n_perms, perm_chunks + 1));
    chunk_list  = cell(perm_chunks,1);
    for cix = 1:perm_chunks
        chunk_list{cix} = (chunk_edges(cix)+1):chunk_edges(cix+1);
    end
    chunk_list = chunk_list(~cellfun(@isempty, chunk_list));
    n_chunks_eff = numel(chunk_list);

    fprintf('  combined designs: %d chunk(s), ~%d permutation(s) each\n', ...
        n_chunks_eff, round(n_perms/n_chunks_eff));

    Cchunks = parallel.pool.Constant(chunk_list);
    chunk_out = cell(n_chunks_eff,1);

    parfor cix = 1:n_chunks_eff
        pidx = Cchunks.Value{cix};
        dsub = Cdesigns.Value(pidx);

        % stack this chunk's designs into one, sets numbered 1..numel(pidx)
        Lc = []; TRc = []; TEc = []; SETc = [];
        for k = 1:numel(dsub)
            nst = size(dsub{k}.label, 2);
            Lc  = [Lc  dsub{k}.label];
            TRc = [TRc dsub{k}.train];
            TEc = [TEc dsub{k}.test];
            SETc = [SETc k*ones(1,nst)];
        end

        cfgC = cfg_template;
        cfgC.design       = dsub{1};
        cfgC.design.label = Lc;
        cfgC.design.train = TRc;
        cfgC.design.test  = TEc;
        cfgC.design.set   = SETc;
        cfgC.design.n_sets = numel(dsub);
        cfgC.design.unbalanced_data = 'ok';
        cfgC.results.setwise = 1;

        r = decoding(cfgC, Cpassed.Value, Cmisc.Value);

        % one output vector per set
        oc = zeros(size(all_perm_results,1), numel(dsub), 'single');
        for k = 1:numel(dsub)
            oc(:,k) = single(r.(outname).set(k).output(:));
        end
        chunk_out{cix} = oc;
        fid_w = fopen(hb_file,'a');
        if fid_w > 0, fprintf(fid_w,'chunk %d (%d perms) %s\n', cix, numel(pidx), datestr(now,'HH:MM:SS')); fclose(fid_w); end
        send(q, numel(pidx));
    end

    for cix = 1:n_chunks_eff
        all_perm_results(:, chunk_list{cix}) = chunk_out{cix};
    end

end

t_perm = toc(t_perm);
fprintf('\n  %d permutations took %.1f s (%.2f s each, %.1fx the true run)\n', ...
    n_perms, t_perm, t_perm/n_perms, (t_perm/n_perms)/max(t_real,eps));
if benchmark_only
    % Project the full-searchlight cost from the decimated one. Cost scales
    % with the number of centres actually decoded, which subset divides.
    % Two separate scalings: the centre count, and the permutation count.
    % The centre factor is total centres / centres actually decoded - NOT the
    % value of searchlight_subset, which is a list of indices rather than a
    % divisor. numel(real_vec) is the number of centres this run decoded.
    n_perms_target  = 200;
    n_centres_run   = numel(real_vec);
    n_centres_total = sum(logical(mask_obj.dat(:)));
    centre_factor   = n_centres_total / max(n_centres_run,1);
    per_perm_full   = (t_perm/n_perms) * centre_factor;
    fprintf('  PROJECTED for the full searchlight:\n');
    fprintf('    centres decoded here  : %d of %d (factor %.1fx)\n', ...
        n_centres_run, n_centres_total, centre_factor);
    fprintf('    true run              ~ %.1f min\n', t_real*centre_factor/60);
    fprintf('    per permutation       ~ %.1f s\n', per_perm_full);
    fprintf('    %d permutations      ~ %.1f h\n', n_perms_target, per_perm_full*n_perms_target/3600);
    fprintf('    NOTE: permutations run single-threaded per worker while the true\n');
    fprintf('          run above gets several cores, so this UNDERSTATES per-perm cost.\n');
end

save(fullfile(tdt_resultsdir,'combined_permutations.mat'), ...
    'all_perm_results','outname','-v7.3');

fprintf('\nCombined null distribution saved.\n');


%% ========================================================================
% 6. VOXELWISE P-VALUES
% ========================================================================

% Stop here on a benchmark run. Everything past this point assumes every
% centre in the mask was actually decoded; with a decimated searchlight the
% un-run centres are zeros indistinguishable from chance-level results.
if benchmark_only
    fprintf(['\n=== BENCHMARK RUN (searchlight_subset = %d): STOPPING BEFORE ' ...
             'INFERENCE ===\n'], searchlight_subset);
    fprintf('  timings above are valid; the maps are NOT. Clear searchlight_subset for a real run.\n');
    return
end

fprintf('\n=== COMPUTING VOXELWISE P-VALUES ===\n');

[V,P] = size(all_perm_results);

exceed = sum(all_perm_results >= real_vec, 2);
p_unc = (exceed + 1) ./ (P + 1);

switch analysis_mode
    
    case 'wholebrain'
        
        results.(performance_metric{1}).p_perm = p_unc;
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');
        
        % Report the result. Without this the mode runs n_perms permutations
        % and prints nothing at all: the headline number - does the classifier
        % separate the groups? - was recoverable only by loading the .mat by
        % hand. TDT returns most metrics multiplied by 100 and stores the
        % matching chancelevel (50 for AUC), so convert back before printing
        % rather than hardcoding a factor. See decoding_statistics.m.
        chance_pct = results.(performance_metric{1}).chancelevel;
        stat_pct   = real_vec(1);
        fprintf('\n=== %s: %s vs %s, n = %d ===\n', ...
            upper(analysis_mode), group_pos_name, group_neg_name, numel(cfg.files.label));
        fprintf('  %-22s %+.2f (chance %g)\n', performance_metric{1}, stat_pct, chance_pct);
        fprintf('  %-22s %.4f\n', 'AUC', (stat_pct + chance_pct)/100);
        fprintf('  %-22s %.4f  (%d permutations)\n', 'permutation p', p_unc(1), P);
        fprintf('  %-22s %.1f\n', 'percentile of null', 100*mean(all_perm_results(1,:) < stat_pct));

        % Report where the null actually sits. It is NOT always at chance, and
        % when it is not, the raw metric cannot be read at face value.
        %
        % Residualizing on nuisance variables fitted over the whole sample
        % couples train and test: within a nuisance level the residuals sum to
        % zero, so subjects in the training folds and subjects in the test fold
        % are pushed in opposite directions. A permutation that preserves the
        % nuisance-label structure aligns that coupling with the labels and the
        % whole null moves below chance. Measured on discoverie T2 (n = 124):
        % the null sat at -9.85 AUC-points with centre residualization plus
        % centre x fold permutation, against -0.20 with free permutation.
        %
        % The TEST is unaffected: observed and null pass through the same
        % pipeline, so they stay exchangeable under H0. Simulated at n = 124
        % over 120 datasets, P(p < .05) came out at 0.050 with a mean p of
        % 0.512, i.e. exactly nominal, and per-training-fold residualization
        % gave the same 0.050. What shifts is the point estimate, not the
        % inference - so read the p-value and the distance from the null, not
        % the AUC on its own.
        null_mu_report = mean(all_perm_results(1,:));
        fprintf('  %-22s %+.2f (sd %.2f)\n', 'null mean', null_mu_report, std(all_perm_results(1,:)));
        if abs(null_mu_report) > 2
            fprintf(['  NOTE: the null is centred %+.2f, not at chance, so the %s above is\n' ...
                     '        shifted by roughly that much. The p-value is still valid; the raw\n' ...
                     '        metric is not comparable to a run with a different null.\n'], ...
                     null_mu_report, performance_metric{1});
        end
        
    case 'roi'
        
        results.(performance_metric{1}).p_perm_unc = p_unc;
        
        % FDR through the lab's canonical implementation, so this script and
        % prep_3a cannot drift apart. It estimates pi0 from Storey's fixed-lambda
        % estimator over a grid, judges whether pi0 is identifiable at all, and
        % returns Benjamini-Hochberg when it is not.
        %
        % The previous inline version took mafdr's spline pi0 and guarded only
        % aprioriprob > 0.99. That catches the conservative failure, not pi0 -> 0:
        % on 8 roi p-values from proj_cfs the spline returned pi0 = 0.012, every q
        % fell below its own p, and the q >= p floor turned the column back into
        % the RAW p-values under the name q. See LaBGAScore_Storey_FDR for the
        % measurements and for how this relates to SAS proc multtest's PFDR.
        [q_fdr, aprioriprob, storey_info] = LaBGAScore_Storey_FDR(p_unc);

        if ~storey_info.reliable
            p_fdr = mafdr(p_unc, 'BHFDR', true);
            results.(performance_metric{1}).p_perm_fdr = p_fdr;
        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_fdr)
                if q_fdr(j) < p_unc(j)
                    q_fdr(j) = p_unc(j);
                end
            end
            results.(performance_metric{1}).q_perm_fdr = q_fdr;
        end
        
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');
        
        % Report per ROI, for the same reason as the wholebrain branch above.
        chance_pct = results.(performance_metric{1}).chancelevel;
        if isfield(results.(performance_metric{1}),'q_perm_fdr')
            corr_vec = results.(performance_metric{1}).q_perm_fdr; corr_lbl = 'q_FDR';
        else
            corr_vec = results.(performance_metric{1}).p_perm_fdr; corr_lbl = 'p_FDR';
        end
        % Straight Benjamini-Hochberg, printed alongside. LaBGAScore_Storey_FDR
        % asks for exactly this at m < 100, and the 'sas' method carries no guard
        % by design - it must reproduce SAS proc multtest - so a spline pi0 well
        % below 1 is USED and shrinks q towards p. Showing both makes that
        % visible instead of leaving the reader one anti-conservative column.
        bh_vec = storey_info.q_BH(:);
        roi_short = cell(numel(roi_list),1);
        for rr = 1:numel(roi_list), [~, roi_short{rr}] = fileparts(roi_list{rr}); end
        fprintf('\n=== ROI: %s vs %s, n = %d, %d permutations ===\n', ...
            group_pos_name, group_neg_name, numel(cfg.files.label), P);
        % 'null' and 'vs null' are not decoration. When nuisance residualization
        % is on, the whole null moves off chance and the raw AUC cannot be read
        % literally: in discoverie T3 the null sat at -23.8 AUC-points, so every
        % roi printed an AUC near 0.33 and looked strongly anti-predictive when
        % in fact each was close to its own null. Print where the null is, and
        % the distance from it, so the table cannot be misread.
        null_mu_roi = mean(all_perm_results, 2);
        null_sd_roi = std(all_perm_results, 0, 2);
        fprintf('  %-42s %8s %8s %8s %9s %9s %9s %9s\n', ...
            'ROI', 'metric', 'AUC', 'null', 'vs null', 'p_unc', corr_lbl, 'q_BH');
        for rr = 1:numel(real_vec)
            z_vs_null = (real_vec(rr) - null_mu_roi(rr)) / max(null_sd_roi(rr), eps);
            fprintf('  %-42s %+8.2f %8.4f %+8.2f %+9.2f %9.4f %9.4f %9.4f\n', ...
                roi_short{min(rr,numel(roi_short))}(1:min(42,end)), real_vec(rr), ...
                (real_vec(rr) + chance_pct)/100, null_mu_roi(rr), z_vs_null, ...
                p_unc(rr), corr_vec(rr), bh_vec(min(rr,numel(bh_vec))));
        end
        if any(abs(null_mu_roi) > 2)
            fprintf(['\n  NOTE: the null is not centred at chance (mean %+.2f over rois), so the AUC\n' ...
                     '        column is offset by roughly that much and is NOT comparable across runs\n' ...
                     '        with different nuisance handling. Read ''vs null'' (in null SDs) and p.\n'], ...
                     mean(null_mu_roi));
        end
        
        
    case 'searchlight'

        results.(performance_metric{1}).p_perm = p_unc;
        
        % Save uncorrected whole-brain p-map
        nii = load_nii(mask_file);
        mask = nii.img > 0;
        mask_idx = find(mask);

        % real_vec must be the real decoding statistics vector
        % used to generate p_unc (same length)
        if length(real_vec) ~= length(p_unc)
            error('real_vec and p_unc length mismatch');
        end

        % Identify valid decoding voxels (NaNs removed by TDT)
        valid_idx = ~isnan(real_vec);

        % Initialize p-map
        pmap = nan(size(nii.img), 'single');

        % Assign only to valid voxels
        pmap(mask_idx(valid_idx)) = p_unc;

        nii.img = pmap;
        save_nii(nii, fullfile(tdt_resultsdir,'p_uncorrected.nii'));
        
        [AUC_stat_obj, AUC_fmri_data, AUC_region_obj, AUC_region_table] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_uncorrected.nii'), results.(performance_metric{1}).output, ...
            mask_obj, atlas, unc_p, ['right-tailed uncorrected p-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'unc', unc_k_auc);
        % Montage of whatever survived. The thresholding function returns a
        % region object and a table but draws nothing, so a surviving result
        % would otherwise be reported as numbers only. The helper returns
        % immediately when there is nothing suprathreshold, so this costs
        % nothing on a null analysis and leaves no empty figures.
        LaBGAScore_blob_montage(AUC_fmri_data, AUC_region_obj, 'AUC unc-thresholded');


        %% ========================================================================
        % 7. WHOLE-BRAIN FDR CORRECTION
        % ========================================================================

        fprintf('\n=== APPLYING FDR CORRECTION ===\n');
        
        fmap = nan(size(nii.img));

        % FDR through the lab's canonical implementation, so this script and
        % prep_3a cannot drift apart. It estimates pi0 from Storey's fixed-lambda
        % estimator over a grid, judges whether pi0 is identifiable at all, and
        % returns Benjamini-Hochberg when it is not.
        %
        % The previous inline version took mafdr's spline pi0 and guarded only
        % aprioriprob > 0.99. That catches the conservative failure, not pi0 -> 0:
        % on 8 roi p-values from proj_cfs the spline returned pi0 = 0.012, every q
        % fell below its own p, and the q >= p floor turned the column back into
        % the RAW p-values under the name q. See LaBGAScore_Storey_FDR for the
        % measurements and for how this relates to SAS proc multtest's PFDR.
        [q_fdr, aprioriprob, storey_info] = LaBGAScore_Storey_FDR(p_unc);

        if ~storey_info.reliable
            p_fdr = mafdr(p_unc, 'BHFDR', true);
            results.(performance_metric{1}).p_perm_fdr = p_fdr;
            fmap(mask_idx(valid_idx)) = p_fdr;
            nii.img = fmap;
            save_nii(nii, fullfile(tdt_resultsdir,'p_FDR.nii'));
            [AUC_stat_obj_fdr, AUC_fmri_data_fdr, AUC_region_obj_fdr, AUC_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_FDR.nii'), results.(performance_metric{1}).output, ...
                mask_obj, atlas, fdr_p, ['right-tailed FDR-corrected p-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'fdr', fdr_k_auc);
            % Montage of whatever survived. The thresholding function returns a
            % region object and a table but draws nothing, so a surviving result
            % would otherwise be reported as numbers only. The helper returns
            % immediately when there is nothing suprathreshold, so this costs
            % nothing on a null analysis and leaves no empty figures.
            LaBGAScore_blob_montage(AUC_fmri_data_fdr, AUC_region_obj_fdr, 'AUC fdr-thresholded');
        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_fdr)
                if q_fdr(j) < p_unc(j)
                    q_fdr(j) = p_unc(j);
                end
            end
            results.(performance_metric{1}).q_perm_fdr = q_fdr;
            fmap(mask_idx(valid_idx)) = q_fdr;
            nii.img = fmap;
            save_nii(nii, fullfile(tdt_resultsdir,'q_FDR.nii'));
            [AUC_stat_obj_fdr, AUC_fmri_data_fdr, AUC_region_obj_fdr, AUC_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'q_FDR.nii'), results.(performance_metric{1}).output, ...
                mask_obj, atlas, fdr_p, ['right-tailed FDR-corrected q-values based on ' num2str(n_perms) ' permutations'], 'AUC', 'fdr', fdr_k_auc);
            % Montage of whatever survived. The thresholding function returns a
            % region object and a table but draws nothing, so a surviving result
            % would otherwise be reported as numbers only. The helper returns
            % immediately when there is nothing suprathreshold, so this costs
            % nothing on a null analysis and leaves no empty figures.
            LaBGAScore_blob_montage(AUC_fmri_data_fdr, AUC_region_obj_fdr, 'AUC fdr-thresholded');
        end

        %% ========================================================================
        % 8. TFCE AND TFCE P-VALUES
        % ========================================================================

        fprintf('\n=== RUNNING TFCE on t-maps ===\n');

        % -------------------- TFCE parameters --------------------
        % Classic TFCE (Smith & Nichols 2009) via tfce_volume. This used to
        % call pTFCE, which is a different algorithm with no H or E parameter:
        % the voxel size was landing in pTFCE's `mask` slot and H/E in its
        % resel-count and voxel-count slots, so the transform was not the one
        % these parameter names describe. See tfce_volume.
        H    = 2;        % Height exponent (Smith & Nichols default)
        E    = 0.5;      % Extent exponent
        conn = 26;       % 3D connectivity
        tfce_sidedness = 'one';   % AUC is tested against 0.5, so one-tailed
        tfce_tail      = 'pos';

        % ========================================================================
        % 0. COMPUTE REAL AND PERMUTATION T-MAPS + EPSILON
        % ========================================================================

        eps_val = 1e-6;     % prevents zero-plateaus that trigger warnings

        % Real t-map
        perm_mu = mean(all_perm_results, 2);
        perm_sd = std(all_perm_results, 0, 2);
        perm_sd(perm_sd == 0) = 1;   % voxels with no variance across permutations

        real_t_vec = (real_vec - perm_mu) ./ perm_sd + eps_val;
        results.(performance_metric{1}).real_t = real_t_vec;

        % Permutation t-maps are NOT materialised as a [V x P] matrix here.
        % Doing so cost a second array the size of all_perm_results (for a
        % 150k-voxel searchlight with 1000 permutations, ~600 MB) and it was
        % then stored in results and written into res_*.mat as well. The two
        % vectors below are all that is needed; each permutation's t-map is
        % formed inside the TFCE loop from its own column, which parfor slices.
        % ========================================================================
        % 1. REAL TFCE MAP
        % ========================================================================

        tmpVol = zeros(size(nii.img), 'single');
        tmpVol(mask_idx(valid_idx)) = single(real_t_vec);

        % The observed map fixes the integration grid; every permutation
        % below reuses tfce_dh so the null is comparable to the observed
        % statistic rather than each map using its own grid.
        [real_TFCE_img, tfce_dh] = tfce_volume(tmpVol, H, E, conn, ...
                                               tfce_sidedness, tfce_tail, []);

        if isempty(tfce_dh)
            error('No positive values in the real t-map: TFCE is identically zero.');
        end
        
        real_TFCE_img(isnan(real_TFCE_img)) = 0;
        real_TFCE_img(real_TFCE_img < 0) = 0;

        real_TFCE_vec = real_TFCE_img(mask_idx(valid_idx));
        results.(performance_metric{1}).real_TFCE = real_TFCE_vec;

        % Save TFCE-enhanced real map
        tfmap = nan(size(nii.img), 'single');
        tfmap(mask_idx(valid_idx)) = real_TFCE_vec;
        nii.img = tfmap;
        save_nii(nii, fullfile(tdt_resultsdir,'TFCE_real.nii'));

        % ========================================================================
        % 2. PARALLEL TFCE NULL DISTRIBUTION (t-maps → TFCE)
        % ========================================================================

        fprintf('Computing TFCE null distribution (parallel)...\n');

        TFCE_null     = zeros(P,1,'single');     % global max TFCE
        TFCE_perm_all = zeros(V,P,'single');     % voxel-wise TFCE
        
        % Progress
        tracker = ProgressTracker(P);
        q_tfce = parallel.pool.DataQueue;
        afterEach(q_tfce, @(~) tracker.update());

        parfor p = 1:P

           tmpVol = zeros(size(nii.img), 'single');
           % t-map for THIS permutation, built from its own column of
           % all_perm_results (a sliced parfor input, so only that column is
           % sent to the worker) rather than from a precomputed [V x P] matrix
           tvec = (all_perm_results(:,p) - perm_mu) ./ perm_sd + eps_val;
           tmpVol(mask_idx(valid_idx)) = single(tvec);

           % Compute TFCE on permutation t-map
           % same integration grid as the observed map
           TFCE_img = tfce_volume(tmpVol, H, E, conn, ...
                                  tfce_sidedness, tfce_tail, tfce_dh);
           
           TFCE_img(isnan(TFCE_img)) = 0;

           TFCE_null(p) = max(TFCE_img(:));         % global max-stat
           TFCE_perm_all(:,p) = TFCE_img(mask_idx(valid_idx)); % voxel-wise TFCE
           
           send(q_tfce,1);
           
        end
        
        TFCE_perm_all(TFCE_perm_all < 0) = 0;

        save(fullfile(tdt_resultsdir,'TFCE_null.mat'),'TFCE_null','TFCE_perm_all');

        % ========================================================================
        % 3. GLOBAL FWE-CORRECTED TFCE p-VALUE (max-statistic)
        % ========================================================================

        TFCE_real_max = max(real_TFCE_vec);

        p_TFCE_global = (sum(TFCE_null >= TFCE_real_max) + 1) / (P + 1);
        
        results.(performance_metric{1}).p_TFCE_global = p_TFCE_global;

        % ========================================================================
        % 4. VOXEL-WISE TFCE p-MAP
        % ========================================================================

        fprintf('Computing voxel-wise TFCE p-values...\n');

        p_TFCE_voxelwise = (sum(TFCE_perm_all >= real_TFCE_vec, 2) + 1) / (P + 1);
        
        results.(performance_metric{1}).p_TFCE_unc = p_TFCE_voxelwise;

        pmap_vox = nan(size(nii.img), 'single');
        pmap_vox(mask_idx(valid_idx)) = p_TFCE_voxelwise;

        nii.img = pmap_vox;
        save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_voxelwise.nii'));
        
        [TFCE_stat_obj, TFCE_fmri_data, TFCE_region_obj, TFCE_region_table] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
            mask_obj, atlas, unc_p, ['right-tailed uncorrected TFCE p-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'unc', unc_k_tfce);
        % Montage of whatever survived. The thresholding function returns a
        % region object and a table but draws nothing, so a surviving result
        % would otherwise be reported as numbers only. The helper returns
        % immediately when there is nothing suprathreshold, so this costs
        % nothing on a null analysis and leaves no empty figures.
        LaBGAScore_blob_montage(TFCE_fmri_data, TFCE_region_obj, 'TFCE unc-thresholded');

        % ========================================================================
        % 5. FDR-CORRECTED TFCE p-MAP
        % ========================================================================

        fprintf('Applying FDR correction to TFCE p-values...\n');
        
        fmap = nan(size(nii.img));

        % FDR through the lab's canonical implementation, so this script and
        % prep_3a cannot drift apart. It estimates pi0 from Storey's fixed-lambda
        % estimator over a grid, judges whether pi0 is identifiable at all, and
        % returns Benjamini-Hochberg when it is not.
        %
        % The previous inline version took mafdr's spline pi0 and guarded only
        % aprioriprob > 0.99. That catches the conservative failure, not pi0 -> 0:
        % on 8 roi p-values from proj_cfs the spline returned pi0 = 0.012, every q
        % fell below its own p, and the q >= p floor turned the column back into
        % the RAW p-values under the name q. See LaBGAScore_Storey_FDR for the
        % measurements and for how this relates to SAS proc multtest's PFDR.
        [q_TFCE_FDR, aprioriprob, storey_info] = LaBGAScore_Storey_FDR(p_TFCE_voxelwise);

        if ~storey_info.reliable
            p_TFCE_FDR = mafdr(p_TFCE_voxelwise, 'BHFDR', true);
            results.(performance_metric{1}).p_TFCE_FDR = p_TFCE_FDR;
            pmap_FDR = nan(size(nii.img), 'single');
            pmap_FDR(mask_idx(valid_idx)) = p_TFCE_FDR;
            nii.img = pmap_FDR;
            save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_FDR_voxelwise.nii'));
            
            [TFCE_stat_obj_fdr, TFCE_fmri_data_fdr, TFCE_region_obj_fdr, TFCE_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_FDR_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
                mask_obj, atlas, fdr_p, ['right-tailed fdr-corrected TFCE p-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fdr', fdr_k_tfce);
            % Montage of whatever survived. The thresholding function returns a
            % region object and a table but draws nothing, so a surviving result
            % would otherwise be reported as numbers only. The helper returns
            % immediately when there is nothing suprathreshold, so this costs
            % nothing on a null analysis and leaves no empty figures.
            LaBGAScore_blob_montage(TFCE_fmri_data_fdr, TFCE_region_obj_fdr, 'TFCE fdr-thresholded');

        else
            % Enforce constraint q >= p (as in SAS proc multtest)
            for j = 1:length(q_TFCE_FDR)
                if q_TFCE_FDR(j) < p_TFCE_voxelwise(j)
                    q_TFCE_FDR(j) = p_TFCE_voxelwise(j);
                end
            end
            results.(performance_metric{1}).q_TFCE_FDR = q_TFCE_FDR;
            qmap_FDR = nan(size(nii.img), 'single');
            qmap_FDR(mask_idx(valid_idx)) = q_TFCE_FDR;
            nii.img = qmap_FDR;
            save_nii(nii, fullfile(tdt_resultsdir,'q_TFCE_FDR_voxelwise.nii'));
            
            [TFCE_stat_obj_fdr, TFCE_fmri_data_fdr, TFCE_region_obj_fdr, TFCE_region_table_fdr] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'q_TFCE_FDR_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
                mask_obj, atlas, fdr_p, ['right-tailed fdr-corrected TFCE q-values based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fdr', fdr_k_tfce);
            % Montage of whatever survived. The thresholding function returns a
            % region object and a table but draws nothing, so a surviving result
            % would otherwise be reported as numbers only. The helper returns
            % immediately when there is nothing suprathreshold, so this costs
            % nothing on a null analysis and leaves no empty figures.
            LaBGAScore_blob_montage(TFCE_fmri_data_fdr, TFCE_region_obj_fdr, 'TFCE fdr-thresholded');

        end
        
        %% ========================================================================
        % 6. VOXEL-WISE TFCE FWE-CORRECTED P-MAP (MAX-STATISTIC)
        % ========================================================================

        fprintf('Computing voxel-wise TFCE FWE-corrected p-values (max-statistic)...\n');

        P = numel(TFCE_null); % number of permutations

        % -------------------------------------------------------------------------
        % Compute voxel-wise TFCE FWE p-values using max TFCE null
        % -------------------------------------------------------------------------
        p_TFCE_FWE_voxelwise = ( ...
           sum(TFCE_null(:)' >= real_TFCE_vec, 2) + 1 ...
           ) ./ (P + 1);
        results.(performance_metric{1}).p_TFCE_FWE = p_TFCE_FWE_voxelwise;
        
        save(fullfile(tdt_resultsdir,['res_' performance_metric{1} '.mat']),'results','-append');

        % -------------------------------------------------------------------------
        % Map vector -> volume
        % -------------------------------------------------------------------------
        pmap_FWE = nan(size(nii.img), 'single');
        pmap_FWE(mask_idx(valid_idx)) = p_TFCE_FWE_voxelwise;

        nii.img = pmap_FWE;
        save_nii(nii, fullfile(tdt_resultsdir,'p_TFCE_FWE_voxelwise.nii'));
        
        [TFCE_stat_obj_fwe, TFCE_fmri_data_fwe, TFCE_region_obj_fwe, TFCE_region_table_fwe] = thresholded_fmri_data_from_pval_nii(fullfile(tdt_resultsdir,'p_TFCE_FWE_voxelwise.nii'), results.(performance_metric{1}).real_TFCE, ...
            mask_obj, atlas, fwe_p, ['right-tailed fwe-corrected TFCE p-values (max statistic) based on ' num2str(n_perms) ' permutations'], 'TFCE', 'fwe', fwe_k_tfce);
        % Montage of whatever survived. The thresholding function returns a
        % region object and a table but draws nothing, so a surviving result
        % would otherwise be reported as numbers only. The helper returns
        % immediately when there is nothing suprathreshold, so this costs
        % nothing on a null analysis and leaves no empty figures.
        LaBGAScore_blob_montage(TFCE_fmri_data_fwe, TFCE_region_obj_fwe, 'TFCE fwe-thresholded');
        
        fprintf('Voxel-wise TFCE FWE-corrected map saved.\n');

        fprintf('\nTFCE completed: FWE, voxel-wise, and FDR TFCE maps saved.\n');

        
        save(fullfile(tdt_resultsdir,'stat_objs.mat'),'AUC_*','TFCE_*');

        
end